### ISSUE TITLE
Add support for named parameters in Native SQL

### ISSUE THREAD

**Issue by raderio** [vincentlauvlwj/Ktorm#101]
Instead of
```
val sql = """
        select name from t_employee
        where department_id = ?
        order by id
    """
```
it will be nice to have
```
val sql = """
        select name from t_employee
        where department_id = :department_id
        order by id
    """
```

https://www.codejava.net/frameworks/spring/spring-namedparameterjdbctemplate-examples

**Comment by vincentlauvlwj** [comment]
Sorry, I'll close this issue because I don't think we should provide more features for native SQLs. 

Although Ktorm provides supports for native SQLs, we don’t encourage people to use it. Once native SQL is used, we will lose the benefits of the strong typed DSL.

**Comment by raderio** [comment]
If someone wants to use only native SQL there are already solutions for this.
Most people which is looking into this library want to use strong typed DSL.
Usually native SQL will be used only when some feature is not available in the library, in this case named parameters in native SQL will be much better than placeholders.
