### ISSUE TITLE
Is it possible to set the value of a variable not as a table field, but as a table field value

### ISSUE THREAD

**Issue by P1NG2WIN** [vincentlauvlwj/Ktorm#103]
I have a table with 4 fields, id, postId, meta_key and meta_value. I want to define a lot of fields in the object of this table, but so that they refer to the value of the field where meta_key is equal to something. Or maybe i can do it somehow while do mapping? Example below

![image](https://user-images.githubusercontent.com/27578886/74737232-17071e00-525d-11ea-8627-717b53617a32.png)

![image](https://user-images.githubusercontent.com/27578886/74737248-1e2e2c00-525d-11ea-8a58-519be9712878.png)

![image](https://user-images.githubusercontent.com/27578886/74737271-2ab28480-525d-11ea-8e7e-5bb242f68f13.png)

![image](https://user-images.githubusercontent.com/27578886/74737477-9e549180-525d-11ea-962f-7d185f3a7e8b.png)

**Comment by vincentlauvlwj** [comment]
Since your table schema doesn't match your entity, you must manually handle the mapping by yourself, like: 

```kotlin
object PostMetas : Table<PostMeta>("post_meta") {
    val metaId by long("meta_id").primaryKey().bindTo { it.metaId }
    val postId by long("post_id").bindTo { it.postId }
    val metaKey by varchar("meta_key").bindTo { it.metaKey }
    val metaValue by varchar("meta_value").bindTo { it.metaValue }
}

interface PostMeta : Entity<PostMeta> {
    var metaId: Long
    var postId: Long
    var metaKey: String
    var metaValue: String
}

data class Post(
    val postId: Long,
    val title: String?,
    val description: String?,
    val keywords: String?
)

fun getPostById(postId: Long): Post {
    val metas = database
        .sequenceOf(PostMetas)
        .filter { it.postId eq postId }
        .associate { it.metaKey to it.metaValue }

    return Post(
        postId = postId,
        title = metas["title"],
        description = metas["description"],
        keywords = metas["keywords"]
    )
}
```

**Comment by P1NG2WIN** [comment]
Thanks a lot! I did this by creating a simple class date, but now I will replace it with your option 

![image](https://user-images.githubusercontent.com/27578886/74810723-aca3bb80-52f8-11ea-87f4-acd9f7124a95.png)

![image](https://user-images.githubusercontent.com/27578886/74810754-bb8a6e00-52f8-11ea-9075-f6d94ffc6bd5.png)
