### ISSUE TITLE
Rollback has no effect when using java.sql.Connection

### ISSUE THREAD

**Issue by AxelG1** [vincentlauvlwj/Ktorm#105]
For schema migration purposes I obtain a `java.sql.Connection`from a `Transaction`obtained via `TransactionManager.newTransaction()`. Then, I create tables and do other things until an exception is raised, upon which I call `rollback()`.

```kotlin
...
// Imagine being in a schema migration context somewhere...
val db = obtainTheCorrectDb()
val trns = db.transactionManager.newTransaction()
val conn = trns.connection    // We use this for native SQL footwork.

try {
    createTable1(conn)    // This table creation will not be rolled back.
    createTable2AndFail(conn)    // This is designed to fail and cause a rollback.
    migrateDataUsingKtormEntities()
    trns.commit()
} catch (ex: Exception) {
    trns.rollback()
    throw ex    // Rethrow for the migration tool.
}
...
```
Before, I tried it directly with the `java-sql.Connection` to the same results. So maybe the issue is not Ktorm-related and someone has an idea of what I am missing/thinking in the wrong direction.
Tested with: v2.6, v2.7.1

Thank you!

**Comment by vincentlauvlwj** [comment]
Can you provide more details? 

Which database? Driver version? Use a connection pool or not? The configuration of the connection pool?

**Comment by AxelG1** [comment]
I'll give more details soon. In the meantime, please don't investigate for there may be other reasons, but I'll know more shortly!

**Comment by AxelG1** [comment]
New findings: it seems like rollback works for all those operations that have been made with KTorm. The creation of tables via SQL are unaffected however.

Ah, and the reason is that DDL statement on some DBMSs (like the one I'm on) aren't transactional. Didn't know. [See here, towards the heading 'Why?'](https://julien.danjou.info/why-you-should-care-that-your-sql-ddl-is-transactional/)
=> not an issue!
