### ISSUE TITLE
Native SQL requst returns nothing in some cases

### ISSUE THREAD

**Issue by P1NG2WIN** [vincentlauvlwj/Ktorm#108]
Hello. For some reason, a query on the native sql returns nothing, although there is data in the database. Could this be due to the fact that the ARTICLE in the table is a char and I put a string? Also, I tried to directly put the number in the request, but still got an empty array (i tried to copy request and execute it in the adminer and I got the result)

Also, I tried this with another product which has a different article, and everything works with it and I get data

Also, I tried to change the article to the ARTICLE in the sql request, but then all queries returns empty result

/////////////
![image](https://user-images.githubusercontent.com/27578886/75177058-192a1a80-573e-11ea-82b6-76293f944c04.png)
//////////////
![image](https://user-images.githubusercontent.com/27578886/75176726-5a6dfa80-573d-11ea-9a5a-35019fd0e840.png)
//////////////
![image](https://user-images.githubusercontent.com/27578886/75178217-5db6b580-5740-11ea-97ac-222b6e594ecf.png)

**Comment by P1NG2WIN** [comment]
Also, literally the same request code from the database does not work if you receive a parameter from  post, but it works if you transmit it by get, in url

![image](https://user-images.githubusercontent.com/27578886/75184363-f18e7e80-574c-11ea-9d31-f9bc103ded98.png)

**Comment by vincentlauvlwj** [comment]
```kotlin
conn.prepareStatement(sql).use { statement ->
    statement.setString(1, article)
    statement.executeQuery()
        .iterable()
        .map { resultSetToList(it) }
        .first()
}
```

Bug in your code: `iterable().map { }` iterates the result set while your `resultSetToList` function also iterates it. 

There is one record in your database. Firstly `iterable.map { }` moves the cursor to the record, then `resultSetToList` moves it to the end without reading any data. That's why your result list is empty.

**Comment by vincentlauvlwj** [comment]
Please correct your code like this: 

```kotlin
conn.prepareStatement(sql).use { statement ->
    statement.setString(1, article)
    statement.executeQuery().use { resultSetToList(it) }
}
```

**Comment by P1NG2WIN** [comment]
Really, it helped. Thanks!
