### ISSUE TITLE
建议把列绑定和table的结合程度降低

### ISSUE THREAD

**Issue by xxxlihui** [vincentlauvlwj/Ktorm#110]
可以把列绑定和table的结合程度较低，同时开放entity内部的map的数据，可以自由组合，这样实现复杂系统的时候可以很好的使用继承，这个框架最好的一点就是entity使用接口组合的方式，通过代理实现真实数据存放，这个很好的

**Comment by vincentlauvlwj** [comment]
把列绑定和table的结合程度降低指的是什么，有一个具体的例子说明吗？

**Comment by xxxlihui** [comment]
发现entity那里已经实现的根据string name来复制值的方法了，这个很方便做重复字段赋值的处理了
