### ISSUE TITLE
uuid值存在问题

### ISSUE THREAD

**Issue by xxxlihui** [vincentlauvlwj/Ktorm#112]
uuid的值到数据里是这样的id=¬í sr java.util.UUID¼™÷˜m…/ J leastSigBitsJ

**Comment by vincentlauvlwj** [comment]
给出你的表结构和具体代码？

**Comment by xxxlihui** [comment]
> 给出你的表结构和具体代码？

https://github.com/xxxlihui/logistictest2
uuid测试.sql就是执行后的数据库备份 mysql5.7

**Comment by vincentlauvlwj** [comment]
MySQL 的驱动不支持直接使用 `UUID` 对象，请改用 `varchar` 函数定义你的字段：

```kotlin
val id by varchar("id")
```
