### ISSUE TITLE
请问, 想填充公共字段, 怎么做?

### ISSUE THREAD

**Issue by itdoer** [vincentlauvlwj/Ktorm#113]
请问, 想填充公共字段, 怎么做?

**Comment by vincentlauvlwj** [comment]
你的提问太简洁了，可以完善一下问题的具体场景吗？

**Comment by itdoer** [comment]
#98 中,我和另外一个兄弟的看法十分雷同
createBy：
createAt：
updateBy：
updateAt：
isDeleted：
备注：

这些都是业务开展时重复出现的细分。
通常我们是：

数据库表设计之初，每个表都有他们。
建议：如果可以让ktorm允许我们创建实体父类，定义公共变量。在其他类中继承父类，
可以免去每个实体类都需要重复出现上面的公共细分
若将来ktorm允许我们这样填充公共分区，更新他们的时机又是什么时候呢？添加
的时候还是插入的时候？
建议：在父类中可以使用注解对个别分段进行标识，例如：@fill（on = Fill.insert）告诉Ktorm插入时候，这个细分的值要更新。
若将来ktorm允许我们做以上两个配置，更新的时机我们配置了，更新的值又应该如何配置呢？
建议：可以放置一下mybatis -plus中的公共分区填充

**Comment by itdoer** [comment]
#98  中，我和另外一个兄弟的看法
十分雷同

**Comment by vincentlauvlwj** [comment]
Ktorm 当然可以定义公共字段，你可以自己写一个 `BaseEntity` 和 `BaseTable`，把你的公共字段都放在父类里面： 

```kotlin
interface BaseEntity<E : BaseEntity<E>> : Entity<E> {
    var createdAt: Instant
    var updatedAt: Instant
    var isDelete: Boolean
}

abstract class BaseTable<E : BaseEntity<E>>(tableName: String) : Table<E>(tableName) {
    val createdAt by timestamp("created_at").bindTo { it.createdAt }
    val updatedAt by timestamp("updated_at").bindTo { it.updatedAt }
    val isDeleted by boolean("is_deleted").bindTo { it.isDelete }
}
```

然后每个业务表都继承父类：

```kotlin
interface User : BaseEntity<User> {
    var id: Long
    var name: String
    var avatar: String
}

object Users : BaseTable<User>("user") {
    val id by long("id").bindTo { it.id }
    val name by varchar("name").bindTo { it.name }
    val avatar by varchar("avatar").bindTo { it.avatar }
}
```
