### ISSUE TITLE
如何在协程中正确执行事务

### ISSUE THREAD

**Issue by RhysXia** [vincentlauvlwj/Ktorm#115]
一般事务是在service层进行的，而数据库操作则是在dao层。当dao中存在协程时，可能会切换线程。

JdbcTransactionManager文件
```kotlin
    override val currentTransaction: Transaction? get() = threadLocal.get()

    override fun newTransaction(isolation: TransactionIsolation): Transaction {
        if (currentTransaction != null) {
            throw IllegalStateException("Current thread is already in a transaction.")
        }

        return JdbcTransaction(isolation).apply { threadLocal.set(this) }
    }
```

Ktorm中事务的管理主要是由`TransactionManager`进行，其中将`Transaction`存储在`ThreadLocal`中，使得当前实现无法正确执行事务。同时，多个协程也可能共享同一线程，从而出现共享一个`Connection`和`Transaction`的情况。

我曾尝试重新实现`TransactionManager`，将`Transaction`和`Connection`存储在协程上下文中。但是没找到合适的实现方式，不知道有没有什么解决方案。谢谢

**Comment by vincentlauvlwj** [comment]
你确定你说的问题存在吗，可否给一个实际的例子？

Ktorm 本身是基于 JDBC 实现的，因此它是一个同步阻塞的 ORM 框架，并不支持协程。比如：

```kotlin
database.useTransaction { tx -> 

}
```

这个函数所接收的闭包并不是 suspend 的，所以你也无法在闭包里面调用 suspend 函数，因此其中不可能存在线程切换。

可能我的理解和你想表达的意思不一样，如果有偏差，麻烦指出。

**Comment by RhysXia** [comment]
```kotlin
suspend fun findAll(): Flow<User> {
    return database.useTransaction {
        println("start")
        delay(1000)
        println("end")
        userDao.findAll()
    }
}
```
以上代码是允许执行的，当多个协程使用同一个线程时，由于是同一个`ThreadLocal`,会导致多个协程的数据库连接和事务都是相同的。
不知道我理解的对不对:)

**Comment by vincentlauvlwj** [comment]
嗯，你给的这段代码确实可以编译通过，但这样的用法是错误的，在协程环境下，确实存在线程切换的可能，导致 `ThreadLocal` 里面保存的事务信息丢失。不仅仅是 Ktorm，其他框架比如 Spring、Hibernate 等都存在相同的问题。

如果希望在协程上下文中传递事务信息，可以借助 `CoroutineContext` 来实现，kotlinx.coroutines 库也提供了一个 `asContextElement` 扩展函数，可以方便地把 `ThreadLocal` 转换成 `CoroutineContext`，可以参考一下：https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/coroutine-context-and-dispatchers.md#thread-local-data

**Comment by vincentlauvlwj** [comment]
但是我不是很建议做这种事情，因为 Ktorm 基于 JDBC 实现，本身就是一个同步阻塞的框架，即使你改造了 `TransactionManager`，也改变不了它阻塞的事实。

现在，我正在计划为 Ktorm 开发一个基于 jasync-sql 的纯异步版本，敬请期待 （虽然不知道什么时候才能发布o(╯□╰)o）

**Comment by RhysXia** [comment]
确实，spring也存在这样的问题，不过spring-data-r2dbc貌似做了做了处理。
我现在想通过ktor构建一个web应用，因为其是基于协程来应答请求的，所以使用ktorm可能会存在问题。
我知道`asContextElement`方法可以保证`ThreadLocal`在协程中的正确运行，不过貌似很难改造`TransactionManager`,也可能我太菜了:(
非常期待`Ktorm`的异步版本

**Comment by RhysXia** [comment]
我现在尝试使用[`Exposed`](https://github.com/JetBrains/Exposed),貌似是可以支持协程中的事务的，目前还没看其中是怎么实现。
我想，既然Ktorm是基于kotlin的库，即使是阻塞式数据库，也应该在协程中保证正确的运行，否则很容易出现多个协程共享连接的情况
