### ISSUE TITLE
Allow to use = instead of delegation on table definition

### ISSUE THREAD

**Issue by raderio** [vincentlauvlwj/Ktorm#116]
At the moment we are using delegation for table properties
```val id by int("id").primaryKey()```
Lets use `=` instead of delegation `by`, as it is more idiomatic.

The main reason to use delegation was to use `val id = int("id").primaryKey()`, functions like `primaryKey`, `bindTo` have to be extensions of `Column`, and column definition functions should be only available when defining table objects. 

This functionality can be achieved if we will have `Colimn` extensions inside `Table class.

```
class Column(val name: String) {

    fun compare(anotherName: String) {

    }
}

open class Table {

    fun int(name: String): Column {
        return Column(name)
    }

    fun Column.primaryKey(): Column {
        return this
    }
}

object Book : Table() {
    val id = int("id").primaryKey() // this method is available only inside table definition
}

fun main() {
    Book.id.primaryKey() // this method is not available here
}
```

**Comment by vincentlauvlwj** [comment]
Added in version 3.0.0
