### ISSUE TITLE
提问一个maven包冲突的问题

### ISSUE THREAD

**Issue by yuzd** [vincentlauvlwj/Ktorm#117]
我现在用的kotlin version 是 1.3.71
me.liuwj.ktorm 的 2.7.2 好像是用的 1.3.60
我
 <dependency>
            <groupId>me.liuwj.ktorm</groupId>
            <artifactId>ktorm-core</artifactId>
            <version>2.7.2</version>
            <exclusions>
                <exclusion>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-reflect</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-stdlib</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
这样配置之后 编译就出问题了

2:19:15 [INFO] --- kotlin-maven-plugin:1.3.71:compile (compile) @ cloudbag-common ---
12:19:42 [ERROR] Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
12:19:42     class me.liuwj.ktorm.schema.BaseTable.ColumnRegistration, unresolved supertypes: kotlin.properties.ReadOnlyProperty
12:19:42 
12:19:42 [ERROR] /var/jenkins_home/workspace/common/CodingUtil.kt: (15, 23) Cannot access built-in declaration 'kotlin.String'. Ensure that you have a dependency on the Kotlin standard library

**Comment by vincentlauvlwj** [comment]
Kotlin 1.3.60 和 1.3.71 是兼容的，可能是你依赖里真的没有把标准库放进去吧...

**Comment by yuzd** [comment]
嗯是的。感谢回复 棒！
