### ISSUE TITLE
Json SQL type

### ISSUE THREAD

**Issue by raderio** [vincentlauvlwj/Ktorm#120]
We are using Json SQL type from PostgreSQL, it will be great to have this in PostgreSQL dialect.

**Comment by vincentlauvlwj** [comment]
JSON SQL type is supported, see https://ktorm.liuwj.me/en/schema-definition.html#Extend-More-Data-Types

**Comment by raderio** [comment]
Ah, I need to add "ktorm-jackson" dependency in the project.
Thank you.
