### ISSUE TITLE
Request for a question

### ISSUE THREAD

**Issue by mattisonchao** [vincentlauvlwj/Ktorm#123]
👀Hi, Vincent. My name is Mattison.
Recently I wanted to build a new project which is ktorm-generator.
But I don't have the right direction.
Therefore, I write this mail and wish you can help me out.

**Comment by vincentlauvlwj** [comment]
ktorm-generator 的目标是要生成 Ktorm 里面的一些样板代码吗，最近有小伙伴写了一个工具，可以了解一下 https://github.com/vincentlauvlwj/Ktorm/issues/14#issuecomment-605449190

**Comment by mattisonchao** [comment]
功能基本一致，只不过我是用的构建工具插件。不过我想把这个工具更加的完善，所以希望得到作者的帮助，并且想了解下你希望的代码生成工具是什么样的。😁

**Comment by yuzd** [comment]
@mattisonchao 我是这个工作的作者，如何更加完善？你有啥想法可以交流下

**Comment by vincentlauvlwj** [comment]
@mattisonchao 首先谢谢你对 Ktorm 的支持，你希望得到哪方面的帮助呢？
