### ISSUE TITLE
Restore result set cursor position

### ISSUE THREAD

**Issue by P1NG2WIN** [vincentlauvlwj/Ktorm#124]
Hello. If i use native sql and after this default ORM then i get error `java.sql.SQLException: Invalid cursor position.` How i can fix it? (If I delete a block with native sql, everything works)

```

            val shops = database.useConnection { conn ->
                val sql = """
                    show columns from PushMe
                    like ?
                """
                conn.prepareStatement(sql).use { statement ->
                    statement.setString(1, "STORE_%")
                    statement.executeQuery()
                        .iterable()
                        .map { it.getString(1) }
                }
            }

            val refList =
                shops.filter {
                    !(it.contains("STORE_STATUS"))
                }.toMutableList()

            val names = ShopWrapper.refactorName(refList)

            val shopOffIds = database
                .from(FIOTable)
                .select()
                .where { FIOTable.storeName inList names }
                .distinctBy { FIOTable.storeName }
                .map { FIOTable.createEntity(it) }
```

![image](https://user-images.githubusercontent.com/27578886/78406828-c3ca0e80-7603-11ea-9041-5506b1c4af22.png)

**Comment by vincentlauvlwj** [comment]
What do you mean by this line?

```kotlin
    .distinctBy { FIOTable.storeName }
```

`distinctBy` is not a function of Ktorm, but an extension of `Iterable` in Kotlin standard lib.

**Comment by vincentlauvlwj** [comment]
`distinctBy` iterates the result set from start to the end, that's why the cursor position invalid. DO NOT iterate the result set twice.

**Comment by P1NG2WIN** [comment]
@vincentlauvlwj Then could you tell me how to select all the lines with the unified field storeName? Processing them after receiving is not an option, there are a lot of them

**Comment by vincentlauvlwj** [comment]
I don't quite understand what you're trying to do? Could you please explain it by showing me a native SQL? Not using Ktorm, just a raw SQL. 

Please try to run your query by writing a SQL first, then I'll tell you how to write the equivalent Kotlin code with Ktorm.

**Comment by P1NG2WIN** [comment]
@vincentlauvlwj 
My decision completely suits me so it does not matter. But, in any case, I googled request that works and does the same, but it seems to be slower, i think

```
SELECT * FROM `tableName`
WHERE `id` IN
(SELECT MIN(`id`) FROM `tableName` GROUP BY `value to distinct`)
```
