### ISSUE TITLE
Query should not implements Iterable

### ISSUE THREAD

**Issue by vincentlauvlwj** [vincentlauvlwj/Ktorm#125]
Some names of extension functions of `Iterable` are misleading. For example: 

- `distinctBy`: #124 
- `groupBy`: this function name exists both in `Query.groupBy` and `Iterable.groupBy`.

**Comment by ragnese** [comment]
It also might lead people to using `Iterable.filter` instead of `Query.where` which would be much worse for performance. The documentation also should warn against this. As it is right now, it actually looks like you *should* use `Iterable.filter` in the examples.

**Comment by vincentlauvlwj** [comment]
You are right. It also lead people to use `Iterable.filter` instead of `Query.where`. This is another reason why `Query` should not implements `Iterable`.

**Comment by vincentlauvlwj** [comment]
Fixed in version 3.0.0
