### ISSUE TITLE
MySQL: Make a bulkInsertOrUpdate

### ISSUE THREAD

**Issue by ragnese** [vincentlauvlwj/Ktorm#127]
Title says it all: There is already `insertOrUpdate` and there's `bulkInsert`. I'd love a `bulkInsertOrUpdate`.

Thanks!

**Comment by ragnese** [comment]
Actually, I found a better way to do what I wanted anyway. I'm not sure if this would be a useful feature, anyway. But I'll leave the issue open.

**Comment by vincentlauvlwj** [comment]
Hmmm...

Since this is really a rare use case, I'd like to postpone it until anyone else asks for that.

**Comment by vincentlauvlwj** [comment]
MySQL does support bulk inserts with `on duplicate key update`: https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html

**Comment by hangingman** [comment]
I want this feature too.

**Comment by vincentlauvlwj** [comment]
Added by @hangingman in version 3.0.0
