### ISSUE TITLE
Why does anonymous object: Iterator<T>::hasNext() call next()?

### ISSUE THREAD

**Issue by ragnese** [vincentlauvlwj/Ktorm#129]
I was having some really strange behavior in my unit tests because of how I was treating the iterator returned from QueryRowSet. 

If I write
```
if (result.hasNext()) {
    val next = result.next()
    /// do stuff
}
```

The iterator has actually advanced TWICE, which is very surprising.

The relevant file is JdbcExtensions.kt, line 106, in version 2.7.2

**Comment by vincentlauvlwj** [comment]
We call `ResultSet.next` to move the cursor forward one row and check if there are more rows, see https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSet.html#next--

**Comment by ragnese** [comment]
I understand what it does, thank you.

I just think it might be incorrect for hasNext() to advance the iterator. Things work fine when you use a for-loop or only call next(). But if you manually use hasNext() and next(), you'll skip rows, won't you?

```
while (result.hasNext()) {
    val foo = result.next()
    // use foo
}
```

**Comment by vincentlauvlwj** [comment]
No, we won't skip rows. Can you show me an example that you think incorrect?

**Comment by vincentlauvlwj** [comment]
For-each loop is just a sugar. It's equivalent to manually using hasNext() and next() in a while loop.

Close this issue because it's not a real problem.
