### ISSUE TITLE
'Order by' with the effects of SQL's 'case'?

### ISSUE THREAD

**Issue by AxelG1** [vincentlauvlwj/Ktorm#131]
I came across a situation where it could be advantageous having something similar to SQL's [CASE](https://www.w3schools.com/sql/sql_case.asp). Especially when using `.orderBy(...)`.
Is there a way to achieve this without leaving the DSL?
Thank you!

**Comment by vincentlauvlwj** [comment]
It's possible to do similar things with Kotlin's `when` expressions: 

```kotlin
val query = database
    .from(Employees)
    .select()
    .orderBy(
        when (sortColumn) {
            "name" -> Employees.name.asc()
            "hiredate" -> Employees.hireDate.asc()
            else -> Employees.id.asc()
        }
    )
```

Is this what you want?

**Comment by AxelG1** [comment]
Imagine joining two Tables `A` and `B`. Say `A` has a column `A.title` and `B` has a column `B.name`, and you want to sort the result and thus cannot rely on a single column for sorting. SQL (all implementations?) provides a construct to deal with this situation, CASE.
I'll investigate further how I can resolve this without falling back to native SQL. Maybe I can use functions in select, I'll report my findings.

**Comment by AxelG1** [comment]
OK, I just found out I could use `concat_ws('', A.title, B.name)` for the same effect. Is there support for functions like `concat_ws`is Ktorm?

**Comment by vincentlauvlwj** [comment]
Write a function by yourself: 

```kotlin
fun concat(separator: String, vararg params: ColumnDeclaring<String>): FunctionExpression<String> {
    return FunctionExpression(
        functionName = "concat_ws",
        arguments = listOf(ArgumentExpression(separator, VarcharSqlType)) + params.map { it.asExpression() },
        sqlType = VarcharSqlType
    )
}
```

Then use it like this: 

```kotlin
val query = database.from(t).select(concat("", t.str1, t.str2))
```

**Comment by AxelG1** [comment]
This is great and seems to work.
