### ISSUE TITLE
audited/ revision feature 

### ISSUE THREAD

**Issue by sysmat** [vincentlauvlwj/Ktorm#135]
* Any plan to have like Hibernate envers (revision of records in DB)
* Any pre/post hooks on entities when doing CRUD

Regards, Tomaž

**Comment by vincentlauvlwj** [comment]
Sorry, no such plans yet. I'm not sure whether it is really neccesarry.

**Comment by sysmat** [comment]
If you developing backend for organization, you need to have revision of your data(when, who, what changed) in some countries it is legal obligation
