### ISSUE TITLE
如何把json转化成表对象

### ISSUE THREAD

**Issue by scorpionfeng** [vincentlauvlwj/Ktorm#136]
参数文档规范,必须使用interface 类型,如下:
interface AppInfo : Entity <AppInfo> {
    companion object : Entity.Factory <AppInfo>()
    val id:Int
    var app_name:String
}
前端  准备好了,json字符 {'id':1,'app_name':'xx'}, 欲将此json字符转换成AppInfo,若使用gson库,该要如何操作

**Comment by vincentlauvlwj** [comment]
暂时不支持 Gson，但是我们提供了 Jackson 的一个插件，把 ktorm-jackson 这个模块添加到依赖里就可以，具体可以参考文档 https://ktorm.liuwj.me/zh-cn/entities-and-column-binding.html#%E5%BA%8F%E5%88%97%E5%8C%96

**Comment by scorpionfeng** [comment]
依然转换不成功, 用起来有点费劲啊
代码:
       objectMapper.findAndRegisterModules()
//        objectMapper.registerModule(KtormModule())
        var app:AppInfo = objectMapper.readValue(receiveText, AppInfo::class.java)

报的异常如下:

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `AppInfo` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (String)"{"id":1,
    "app_name": "appname",
    "db_name": "dbname",
    "db_user": "user",
    "db_pwd": "pwd",
    "db_port": 8080,
    "dir_out": "dirout"
}"; line: 1, column: 1]

**Comment by vincentlauvlwj** [comment]
因为你把 `objectMapper.registerModule(KtormModule())` 这行注释掉了。。。。
