### ISSUE TITLE
更新表无面向对象API

### ISSUE THREAD

**Issue by scorpionfeng** [vincentlauvlwj/Ktorm#139]
将数据传至接口时,先查出对应ID的表数据,需要将值重新get/set,太不方便,代码如下
有没有直接将接口的对象覆盖进 序列的API?  这样用起来太不方便

post<RouteAppinfo.Update>{
        val form=call.receiveText()
        val form_appinfo=jackson.readValue(form,AppInfo::class.java)
        sequence.find { it.id eq form_appinfo.id }?.apply {

            **_this.app_name=form_appinfo.app_name
            this.db_name=form_appinfo.db_name_**

            val amount=flushChanges()
            call.respond(mapOf("success" to (amount>0),"message" to "changed $amount "))
        }

            ?:apply {
            call.respond(mapOf("success" to false,"message" to "id not exist"))
        }

    }

**Comment by vincentlauvlwj** [comment]
情况文档：https://ktorm.liuwj.me/zh-cn/dml.html#%E6%9B%B4%E6%96%B0

**Comment by scorpionfeng** [comment]
你发的是dsl级别的,我需要的是实体类的API,对比,springboot的 update操作, 或者是说明这个框架暂不支持,需要自己实现呢?

**Comment by vincentlauvlwj** [comment]
我不知道你说的 spring boot 的 update 操作是什么...

**Comment by vincentlauvlwj** [comment]
你想要做到什么效果，可以写几行伪代码表达一下

**Comment by scorpionfeng** [comment]
好的

**_
post<RouteAppinfo.Update>{
val form=call.receiveText()
val form_appinfo=jackson.readValue(form,AppInfo::class.java) // form_appinfo类为前端json转换形成的数据对象类
val table= sequence.find { it.id eq form_appinfo.id } // 通过序列查出数据库中对应的数据
 val amount= table.update(form_appinfo) // 此行为伪代码, 期望 直接用 form_appinfo 对象的值  覆盖写入 序列对象对应的 行
}

_**

**Comment by vincentlauvlwj** [comment]
我明白了，之前有人也问过同样的问题，我在那里给出了一个解决方案，可以看一下 https://github.com/vincentlauvlwj/Ktorm/issues/31#issuecomment-518241613
