### ISSUE TITLE
How about Entity base save method ?

### ISSUE THREAD

**Issue by hangingman** [vincentlauvlwj/Ktorm#140]
relates #87

I would like to save data like `database.save(entities)`.
I've create some snippet like following: 

```kotlin
    fun <E : Any> save(db: Database, entity: E, table: BaseTable<E>) {
        db.insert(table) {
            val sortedColumns = table.columns.sortedBy { it.name }
            val sortedProps = entity::class.memberProperties.sortedBy { it.name }

            sortedColumns.zip(sortedProps).forEach { (col, prop) ->
                it[col.name] to prop.getter.call(entity)
            }
        }
    }

    fun <E : Any> save(db: Database, entities: List<E>, table: BaseTable<E>) {
        db.batchInsert(table) {
            for (entity in entities) {
                val sortedColumns = table.columns.sortedBy { it.name }
                val sortedProps = entity::class.memberProperties.sortedBy { it.name }

                item {
                    sortedColumns.zip(sortedProps).forEach { (col, prop) ->
                        it[col.name] to prop.getter.call(entity)
                    }
                }
            }
        }
    }
```

- The point of this code is, we can insert data without specifying column assignment
- But, this will not work if there is any big difference between table column name and Entity property name 
- I'm happy if `database.insert` and `database.batchInsert` have such method
  - I imagine method signature like:

```kotlin
db.insert(table, entity)
db.batchInsert(table, entities)
```

What do you think ?

**Comment by vincentlauvlwj** [comment]
It is already implemented, use it like `database.sequenceOf(Employees).add(employee)`.

The document is here https://ktorm.liuwj.me/en/entity-dml.html#Insert

**Comment by hangingman** [comment]
@vincentlauvlwj Thank you. I've understand the meaning of sequence API.
However, I now started using data class as Entity, so it's impossible to use sequence API.
For now, I will just use my utility save method with Kotlin's extension function.
