### ISSUE TITLE
What is the purpose of the SqlExpressionVisitor subclasses in the dialects?

### ISSUE THREAD

**Issue by arustleund** [vincentlauvlwj/Ktorm#142]
Hi there! I recently discovered this project and I'm really enjoying using it so far. I am using some Postgres extensions and so need to write my own dialect to add some new expressions.

I was looking at the existing dialects as an example and I was confused by the SqlExpressionVisitor subclasses declared in the main dialect source file, for example `PostgreSqlExpressionVisitor `. Where is this class used and why is it necessary? I don't see it being used or loaded anywhere.

I implemented by own dialect and didn't include this class and everything seems to be working fine. Am I missing something? Thanks!

**Comment by vincentlauvlwj** [comment]
By designed, every expression class should have a `visitXxx` function in the visitor. For `BinaryExpression`, we have `visitBinary`. For `UnaryExpression`, we have `visitUnary`. 

But for dialect expression classes, we cannot add those `visitXxx` functions to the visitor class, because the super class is in the core module. That's why I created `PostgreSqlExpressionVisitor`. 

Yes, this class is not used by now. It just provides a convenience for third-party libraries and user-custom dialects.

**Comment by arustleund** [comment]
Thanks for the quick response? I'm still a little confused. Could you maybe provide an example or further explanation as to when you might use this class? As far as I can tell, when you implement a new dialect, you just need to extend the `SqlFormatter` class, right? Thanks again for your quick response.

**Comment by vincentlauvlwj** [comment]
I just got an example. Assuming that we want to check whether there is an `ILikeExpression` in a query, we can use this class and write a function like follows: 

```kotlin
fun hasILike(select: SelectExpression): Boolean {
    var hasILike = false

    val visitor = object : PostgreSqlExpressionVisitor() {
        override fun visitILike(expr: ILikeExpression): ILikeExpression {
            hasILike = true
            return expr
        }
    }

    visitor.visit(select)
    return hasILike
}
```

The `ILikeExpression` is a dialect expression class for Postgres. There is not a `visitILike` function in `SqlExpressionVisitor`, then we have to provide a subclass in the dialect module to support that usage. 

It's possible that a third-party library or a user-custom dialect would access the expression tree, so providing `PostgreSqlExpressionVisitor` is necessary, although it's not used by now.
