### ISSUE TITLE
Allow easier extension of BinaryExpression

### ISSUE THREAD

**Issue by arustleund** [vincentlauvlwj/Ktorm#143]
Hi! I really love this library, thanks!

I am using a Postgres extension that includes a few custom operators that I would like to use. It seemed simplest to me to simply add a new function that would return a BinaryExpression to my codebase. However, since the BinaryExpressionType is an enum, I cannot add my new operator.

Defining a whole new dialect or modifying the Postgres dialect seemed like overkill when I could achieve the same result by simply defining a function (if I could pass my own operator to the BinaryExpression constructor).

**Comment by vincentlauvlwj** [comment]
Instead of making `BinaryExpression` extensible, I'd prefer add those operators you mentioned to the Postgres dialect, so please let me know what operators you want.

**Comment by arustleund** [comment]
I'm adding partial support for the hstore type: [https://www.postgresql.org/docs/9.0/hstore.html](url) As you can see, there are several special operators for working with this type. I only needed to implement one of them for my purposes. I've added a few new `SqlType`s, and a new `ScalarExpression` to achieve this in my code. All of these operators would work exactly like the `BinaryExpression` class with a narrower type focus.

**Comment by arustleund** [comment]
I think I'll work on a quick pull request to add hstore support, since it may be beneficial to others.

**Comment by vincentlauvlwj** [comment]
Great!! Looking forward to your contributions!

**Comment by arustleund** [comment]
Just submitted pull request #144
