### ISSUE TITLE
执行解析速度慢, excute sql or parse sql  slowly

### ISSUE THREAD

**Issue by pan6465190** [vincentlauvlwj/Ktorm#149]
您好:
   我在使用ktorm执行普通查询测试速度，发现比JDBC 慢 10倍左右,
  代码如下：
        var rowSet = database.from(kw_distributeuser).select().rowSet
 #1.表中数据15条，单次平均耗时0.04s // 获取连接速度0.0s   sql执行速度--0.04s
 #2.使用Jdbc查询单次平均耗时0.004s   // 获取连接速度0.0s   sql执行速度--0.004s
**环境 springboot java+kotlin+mysql混合使用**
  目前大家都是这样么？

**Comment by pan6465190** [comment]
我的使用方式
Springboot中 java和kotlin混合使用
,断点测试速度主要慢在解析执行那一步。

**Comment by pan6465190** [comment]
Hello!
I'm using ktorm to perform common query tests, and find that it's about 10 times slower than JDBC,
The code is as follows:
var rowSet = database.from (kw_ distributeuser).select().rowSet
#1. There are 15 pieces of data in the table. The average time of each time is 0.04s / / the connection speed is 0.0s. The SQL execution speed is - 0.04s
#2. The average time of a single query using JDBC is 0.004s / / the connection speed is 0.0s and the SQL execution speed is - 0.004s
Is that everyone is doing now?

**Comment by vincentlauvlwj** [comment]
性能评估不是一件简单的事情，很容易受到各种因素影响，不要轻易下结论。你可以提供一下你的具体代码和执行环境的信息吗？

**Comment by pan6465190** [comment]
系统 windows
数据库 mysql
代码用例 [https://pan.baidu.com/s/1mkOCqrMdvdB8pBOcOj1NZA](url)
提取码：s59j
是我用的不对么，今天早上又测试了一下,感觉orm好像没走mysql querycache
有QQ交流群么。

**Comment by pan6465190** [comment]
![image](https://user-images.githubusercontent.com/18241968/82743466-9cd7bf80-9d9e-11ea-840d-3a921228e7a4.png)
测试代码入口

**Comment by BiyuHuang** [comment]
Any updates on this issue ??
