### ISSUE TITLE
PostgreSQL dialect query fails when using inList on empty list

### ISSUE THREAD

**Issue by JoonasC** [vincentlauvlwj/Ktorm#151]
With PostgreSQL, when performing a query that uses the inList function eg: `database.delete(Foo) { it.someId inList idsOfStuffToDelete }`, the query will fail if the list (idsOfStuffToDelete) is empty.
It seems that PostgreSQL considers the `()` symbols in the resulting SQL query as invalid syntax, and throws an error.

**Comment by vincentlauvlwj** [comment]
Yes, this is by design. It is users' resposibility to check if the collection is empty. 

```kotlin
if (idsOfStuffToDelete.isNotEmpty()) {
    database.delete(Foo) { it.someId inList idsOfStuffToDelete }
}
```
