### ISSUE TITLE
Sql Substring function support

### ISSUE THREAD

**Issue by Tmilly** [vincentlauvlwj/Ktorm#153]
I have to join two tables on a substring of one Column<String> to another Column<String>.

 As far as I am aware, there isn’t a substring function to achieve this in ktorm. Is there another solution to do this without writing a native query?

**Comment by vincentlauvlwj** [comment]
https://github.com/vincentlauvlwj/Ktorm/issues/131#issuecomment-623475925

Check this issue. It's easy to support custom functions in Ktorm.

**Comment by vincentlauvlwj** [comment]
Ktorm doesn't have a substring function yet. You can implement this by writing a Kotlin function that returns a `FunctionExpression`. 

Do not hesitate to contact me if you have any question.

**Comment by Tmilly** [comment]
Is it possible to then group by these custom functions as you can in sql? Compiler is telling me to group by the column in question or by aggregate function when I’m trying to group by my custom substring function on the column in question.

**Comment by Tmilly** [comment]
I was able to resolve this by aliasing the custom functionExpression for the given column and made sure to use that alias within my group by instead of referencing the table column itself.

**Comment by vincentlauvlwj** [comment]
Can you show me your code?

**Comment by tzhao11** [comment]
This is my approach to `substr`:
```kotlin
fun ColumnDeclaring<String>.substr(position: Int, length: Int? = null): FunctionExpression<String> {
    return FunctionExpression(
        functionName = "substr",
        arguments = listOf(asExpression(), ArgumentExpression(position, IntSqlType)) + length?.let { listOf(ArgumentExpression(it, IntSqlType)) }.orEmpty(),
        sqlType = VarcharSqlType
    )
}
```
