### ISSUE TITLE
The link https://ktorm.liuwj.me/ is dead (with VPN)

### ISSUE THREAD

**Issue by scorsi** [vincentlauvlwj/Ktorm#157]
Issue written in the title :)

**Comment by scorsi** [comment]
Oh my bad... It's due to my VPN. It is a china hosted website ?

**Comment by scorsi** [comment]
Is everything of the website available here : https://github.com/vincentlauvlwj/Ktorm/tree/master/docs/source/en ? :)

**Comment by vincentlauvlwj** [comment]
> Is everything of the website available here : https://github.com/vincentlauvlwj/Ktorm/tree/master/docs/source/en ? :)

Yes, you can get all the documents here if ktorm.liuwj.me is not available in your country.
