### ISSUE TITLE
Request support for `java.sql.Types.CHAR`/`kotlin.Char`

### ISSUE THREAD

**Issue by scorsi** [vincentlauvlwj/Ktorm#158]
Hello,

I need to use chars in my database, using varchar could results on errors.

My actual workaround:

```kotlin
object CharSqlType : SqlType<Char>(Types.CHAR, typeName = "char") {
    override fun doSetParameter(ps: PreparedStatement, index: Int, parameter: Char) {
        ps.setString(index, parameter.toString())
    }

    override fun doGetResult(rs: ResultSet, index: Int): Char? {
        return rs.getString(index)?.getOrNull(0)
    }
}

fun BaseTable<*>.char(
    name: String
): Column<Char> {
    return registerColumn(name, CharSqlType)
}
```

I can create the PR if you're okay ? =)

_PS: I have the same need for `short` and I achieve to use the quite same feature right here._

Thanks !

**Comment by vincentlauvlwj** [comment]
But the `CHAR` SQL type can contain multiple characters, so it is not equivelent to `kotlin.Char`. It should be `kotlin.String` instead. 

See https://dev.mysql.com/doc/refman/8.0/en/char.html

**Comment by scorsi** [comment]
In fact, I used `CHAR` but as you said, I could use `VARCHAR` I often used `CHAR` in my SQL since it was more optimized in PostgreSQL for big data (not for space but for searching).

The can understand that a `kotlin.Char` is not really used for database by people, but I do.
What for `kotlin.Short`/`java.sql.Types.SMALLINT` ?
```kotlin
object ShortSqlType : SqlType<Short>(Types.SMALLINT, typeName = "short") {
    override fun doSetParameter(ps: PreparedStatement, index: Int, parameter: Short) {
        ps.setString(index, parameter.toInt())
    }

    override fun doGetResult(rs: ResultSet, index: Int): Short? {
        return rs.getString(index).toShort()
    }
}

fun BaseTable<*>.short(
    name: String
): Column<Short> {
    return registerColumn(name, ShortSqlType)
}
```

**Comment by vincentlauvlwj** [comment]
`kotlin.Short` is OK.
