### ISSUE TITLE
Is it possible to print the given query ?

### ISSUE THREAD

**Issue by scorsi** [vincentlauvlwj/Ktorm#159]
Hello,

Just to be sure my queries are correctly made, I would like to print the given SQL instead of analysing the query AST. Is it possible ?

Thanks !

**Comment by vincentlauvlwj** [comment]
Ktorm prints SQLs at `DEBUG` log level, you need to configure your logging framework to enable it. 

See https://ktorm.liuwj.me/en/connect-to-databases.html#Logging

**Comment by scorsi** [comment]
@vincentlauvlwj oops, I missed that, thanks !
