### ISSUE TITLE
关于SpringBoot使用的问题

### ISSUE THREAD

**Issue by hslooooooool** [vincentlauvlwj/Ktorm#16]
可以添加使用SpringBoot进行开发的案例Demo么？感谢。

**Comment by hslooooooool** [comment]
![20190517092549](https://user-images.githubusercontent.com/22020721/57896980-f4874500-7885-11e9-86ce-11be0a04e556.jpg)

# 16 问题来源于此异常，期望得到您的解决。

**Comment by vincentlauvlwj** [comment]
关于 Spring 框架的集成，可以参考文档中 Spring 支持一节：https://ktorm.liuwj.me/zh-cn/spring-support.html

如果你需要的是一个可以直接运行的简单 demo，我这两天会新建一个 repo，介绍如何在 Spring Boot 中使用 Ktorm

**Comment by vincentlauvlwj** [comment]
你的这个异常应该是在加载 `Employees` 类的时候出现了错误，能否看一下这个类定义的代码

**Comment by vincentlauvlwj** [comment]
刚刚上传了一个使用 Spring Boot 的 demo，这个 demo 是可以直接运行的：https://github.com/vincentlauvlwj/ktorm-example-spring-boot

但是你遇到的问题应该与 Spring Boot 的集成无关，可以给出更多的代码吗，这样我们才能方便找到问题

**Comment by hslooooooool** [comment]
非常感谢您的demo，我正在对比排查问题。目前可能是由于duird版本和spring boot版本导致，我正在尝试升级。如果您打算支持springboot1.x，duird1.1.3，我想我可以把项目代码发送给您，如果您不需要支持到低版本，我尝试处理后如果无法解决或完成解决，我都将反馈给您。




------------------ 原始邮件 ------------------
发件人: Vincent Lau <notifications@github.com>
发送时间: 2019年5月17日 12:21
收件人: vincentlauvlwj/Ktorm <Ktorm@noreply.github.com>
抄送: 华清松 <821034742@qq.com>, Author <author@noreply.github.com>
主题: 回复：[vincentlauvlwj/Ktorm] 关于SpringBoot使用的问题 (#16)




刚刚上传了一个使用 Spring Boot 的 demo，这个 demo 是可以直接运行的：https://github.com/vincentlauvlwj/ktorm-example-spring-boot
 
但是你遇到的问题应该与 Spring Boot 的集成无关，可以给出更多的代码吗，这样我们才能方便找到问题

**Comment by vincentlauvlwj** [comment]
Ktorm 对 Spring Boot 的版本并没有要求哦，低版本也是可以

**Comment by hslooooooool** [comment]
> Ktorm 对 Spring Boot 的版本并没有要求哦，低版本也是可以

我已经上传了我的Demo代码：https://github.com/hslooooooool/ktorm-demo      目前错误还没有解决。

**Comment by vincentlauvlwj** [comment]
我看了你的代码，发现如下几个问题：

1. Spring Boot 配置文件中的 driver-class-name, url, username, password 等属性配置错误，你把它们写在了 spring.datasource.druid 下，实际上应该是 spring.datasource

2. 表对象 Employees 里面的字段，没有调用 bindTo 方法绑定到实体类的属性上，具体使用方法可以参考文档中列绑定一节：https://ktorm.liuwj.me/zh-cn/entities-and-column-binding.html#%E5%88%97%E7%BB%91%E5%AE%9A

3. Result 类里面的 put 函数调用了 set 函数，然而在 Kotlin 中 Map 的 set 函数里面也调用了 put 函数，从而产生了无限递归导致栈溢出

最后，在解决完这几个问题之后，我再稍作修改就成功把你的项目跑了起来，与 Ktorm 的集成也完全正常，并没有出现你之前说到的情况。

总结：你遇到的问题既与 Spring Boot 无关，也与 Ktorm 无关，更加与任何第三方框架都无关。

**Comment by hslooooooool** [comment]
非常感谢，这个在之前的配置中运行没有出现问题所以没有在意配置问题(之前完全用的jpa)，我将按照您的办法处理，后续用您的框架做项目，它非常方便、强大，再次谢谢。

**Comment by vincentlauvlwj** [comment]
不客气，感谢你对 Ktorm 的支持
