### ISSUE TITLE
Android connection  

### ISSUE THREAD

**Issue by fail572872916** [vincentlauvlwj/Ktorm#17]
我得到了以下错误
![333333](https://user-images.githubusercontent.com/19763500/57868722-18bb3580-7836-11e9-8e73-7c4d0242efd4.png)

**Comment by vincentlauvlwj** [comment]
要使用 MySQL 数据库的话，你需要在 gradle 依赖中添加 MySQL 的 JDBC 驱动，比如：

```groovy
implementation "mysql:mysql-connector-java:8.0.13"
```

另外，我注意到你这是一个 Android 项目，Ktorm 是基于 JDBC 实现的，在 Android 中使用 JDBC 理论上也是可以的。但是你代码中写的数据库地址是 `localhost:3306`，你确定在你的 Android 手机或者模拟器上有运行 MySQL 的服务吗？

**Comment by fail572872916** [comment]
最终，我以失败告终。
