### ISSUE TITLE
Recommend a common pagination tool 

### ISSUE THREAD

**Issue by fangjinuo** [vincentlauvlwj/Ktorm#19]
Use [sqlhelper](https://github.com/fangjinuo/sqlhelper), it is unnecessary to build a module for each database

**Comment by vincentlauvlwj** [comment]
Thanks for your suggestion, but those modules are designed not just for pagination. They also provides many database specific operators, DSL syntax and SQL functions, such as PostgreSQL's `ilike` operator, MySQL's `bulkInsert` DSL, `insertOrUpdate` DSL, `jsonContains ` function, and so on.

**Comment by vincentlauvlwj** [comment]
So you known, Ktorm is much more than a "pagination tool", and we currently do not need to build on something like yours. 

Nevertheless, congratulations for publishing your open source project and good luck to you.
