### ISSUE TITLE
Make Ktorm multiplatform

### ISSUE THREAD

**Issue by lamba92** [vincentlauvlwj/Ktorm#21]
Would it be possible to make this library multiplatform? I guess that most of the SQL generation code may be already JVM independent. 
I suppose the connection of course is not of course.

**Comment by vincentlauvlwj** [comment]
Well, there could be a lot of works to do. 

Ktorm focuses on the JVM platform and tightly depends on many infrastructures of Java, such as reflect and JDBC. Of course the biggest problem here is JDBC. To make Ktorm multi-platform, we have to remove JDBC, and write a lot of code to handle connections for different databases on each platform. :weary:

Ktorm works well on JVM now. I don't think it's really necessary to support kotlin-js/kotlin-native for server-side applications. JVM is good enough.

**Comment by lamba92** [comment]
> Ktorm works well on JVM now. I don't think it's really necessary to support kotlin-js/kotlin-native for server-side applications. JVM is good enough.
And I do agree with you. 

Yet in many scenarios - **cof cof** AWS Lambda cold start **cof cof** - JS is still way to more convenient then JVM. 
Native still has a long way to go of course.
