### ISSUE TITLE
Does it work with SQLDroid drivers?

### ISSUE THREAD

**Issue by lamba92** [vincentlauvlwj/Ktorm#22]
SQLite databases are often used in Android apps. Unfortunately the Xerial drivers [are bugged](https://github.com/xerial/sqlite-jdbc/issues/248) for Android and the only viable JDBC driver are the [SQLDroid](https://github.com/SQLDroid/SQLDroid) ones. Since the JDBC URL is different from the SQLite one, would it work?

**Comment by vincentlauvlwj** [comment]
I'm afraid to say no.

Technically, Ktorm is implemented based on JDBC, so any database that provides a JDBC driver should be supported naturally. However, I notice that SQLDroid's JDBC implementation is not so completed. You can see there are many methods that throws `UnsupportedOperationException` in [SQLDroidResultSetMetaData](https://github.com/SQLDroid/SQLDroid/blob/master/src/main/java/org/sqldroid/SQLDroidResultSetMetaData.java). Unfortunately, Ktorm uses these methods indirectly via [CachedRowSet](https://docs.oracle.com/javase/8/docs/api/javax/sql/rowset/CachedRowSet.html).

I'm refactoring my code to remove the usage of `CachedRowSet`. So maybe in the next release, SQLDroid will be supported.

**Comment by vincentlauvlwj** [comment]
Ktorm 2.6 released. Now, it is available for Android SQLite with the support of SQLDroid driver.

**Comment by vincentlauvlwj** [comment]
And technically, any other JDBC driver is also supported (if you really need them running on Android).
