### ISSUE TITLE
How to deserialize from JSON?

### ISSUE THREAD

**Issue by lamba92** [vincentlauvlwj/Ktorm#31]
Say you are exposing some REST endpoint and the client POSTs you a modified entity, is it possible to deserialize it directly in a Ktorm object? If so, can you update the entity on the database as well?

**Comment by vincentlauvlwj** [comment]
Ktorm provides a Jackson extension that supports serializing entity objects into JSON format and parsing JSONs as entity objects. You need to add it to your dependencies: 

```groovy
compile "me.liuwj.ktorm:ktorm-jackson:${ktorm.version}"
```

Then create an `ObjectMapper` and register the extension to it: 

```kotlin
val objectMapper = ObjectMapper()
objectMapper.registerModule(KtormModule())
```

Now you can use this mapper to deserialize entity objects from JSONs: 

```kotlin
val employee = objectMapper.readValue(json, Employee::class.java)
```

However, updating the deserialized entity to the database is not supported. That's because Ktorm only saves entities’ property values when serialization, any other data that used to track entity status are lost (marked as transient). So we can not obtain an entity object from one system, then flush its changes into the database in another system.

If you try to call the `flushChanges` function on a deserialized entity, you will get an exception: 

```plain
java.lang.IllegalStateException: The entity is not associated with any table yet.
```

**Comment by lamba92** [comment]
Is there any way to automate the recovery of the entity by `id` and update its fields accordingly to the JSON and return the object?

**Comment by lamba92** [comment]
That would be amazing for REST repositories, espiacially for ktor

**Comment by vincentlauvlwj** [comment]
Sorry, I can't get your point. Could you explain it in detail?

**Comment by lamba92** [comment]
Here's what i have in mind. Given a JSON string containing at least the ID:
 - fetch the entity from the database
 - update all fields present in the JSON string
 - return the already updated object

That would turn the very act of JSON deserialization a convenient way to update data on the database. That's basically what Spring does when creating a [rest repositories](https://spring.io/projects/spring-data-rest).

**Comment by vincentlauvlwj** [comment]
I wrote an extension function which might help you: 

```kotlin
fun <E : Entity<E>> Table<E>.updateColumnsByEntity(entity: E): E {
    val primaryKey = this.primaryKey ?: error("Table $tableName doesn't have a primary key.")

    val primaryKeyName = (primaryKey.binding as NestedBinding).properties[0].name
    val primaryKeyValue = entity[primaryKeyName] ?: error("The value of the primary key is absent.")

    val entityFromDb = this.findById(primaryKeyValue) ?: error("Entity not found for id: $primaryKeyValue")

    for ((name, value) in entity.properties) {
        if (name != primaryKeyName && value != null) {
            entityFromDb[name] = value
        }
    }

    entityFromDb.flushChanges()
    return entityFromDb
}
```

Assuming we have a `Departments` table which is given as follows: 

```kotlin
interface Department : Entity<Department> {
    val id: Int
    var name: String
    var location: String
}

object Departments : Table<Department>("t_department") {
    val id by int("id").primaryKey().bindTo { it.id }
    val name by varchar("name").bindTo { it.name }
    val location by varchar("location").bindTo { it.location }
}
```

The usage of that extension function is simple (using Spring MVC): 

```kotlin
@RestController
class DepartmentController {

    @PostMapping(path = ["/departments"])
    fun updateDepartment(@RequestBody department: Department): Department {
        return Departments.updateColumnsByEntity(department)
    }
}
```

You can copy that function to your project. Hope this might help you.

**Comment by yuzd** [comment]
我觉得你写的根据主键update这个扩展方法应该可以框架层面包装下，insert也可以这么包装。spring在json接收为entity对象后可以直接操作确实很方便

**Comment by yuzd** [comment]
Then create an ObjectMapper and register the extension to it:

val objectMapper = ObjectMapper()
objectMapper.registerModule(KtormModule())
Now you can use this mapper to deserialize entity objects from JSONs:

val employee = objectMapper.readValue(json, Employee::class.java)
我按照你的这个方式
报错了。原因是因为 我的这个json里面的时间是特出处理过的，

![image](https://user-images.githubusercontent.com/16083659/62536800-7c775c80-b881-11e9-9611-ea9a8c55c4fc.png)

请教下 我可以怎么能针对这种的时间字符串自定义parse逻辑吗？

**Comment by lamba92** [comment]
@vincentlauvlwj ti be sure I understood correctly, I can deserialize the entity using jackson, then feed the entity to the extension method to update its fields on his respective table and return it. Right?

**Comment by vincentlauvlwj** [comment]
@lamba92 Yes, you are right.

**Comment by vincentlauvlwj** [comment]
@yuzd 同学，你这题超纲了。。。

理论上你这个问题与 Ktorm 无关，应该去找找 Jackson 的相关文档，或者在 Jackson 的社区上提问，我只是顺手回答一下：

```kotlin
val deserializer = object : JsonDeserializer<LocalDateTime>() {
    override fun deserialize(p: JsonParser, ctxt: DeserializationContext): LocalDateTime {
        val str = p.valueAsString // Date(1565089204000-0000)
        TODO("在这里把你的字符串解析成 LocalDateTime")
    }
}

objectMapper.registerModule(object : SimpleModule() {
    init {
        addDeserializer(LocalDateTime::class.java, deserializer)
    }
})
```

上面这段代码在 objectMapper 中注册了一个简单的插件，这个插件只包含了一个针对 `LocalDateTime` 的反序列化器，你把它 copy 到你的项目中，然后在 `TODO` 的地方按照你的格式自己把字符串解析成 `LocalDateTime` 对象就好了

**Comment by yuzd** [comment]
非常感谢大神教育，膜拜膜拜。谢谢
