### ISSUE TITLE
Ktorm返回查询数据的对应实体类对象,是否是忽略掉了那些为null的字段?

### ISSUE THREAD

**Issue by stars-one** [vincentlauvlwj/Ktorm#336]
**目前我是想要在返回数据的时候把该有的字段都返回给前端**,如查询用户详情的时候,sex如果为null也给个空白字符串

我查阅的网上的方法,配置了jackson的objectmapper,但是实际测试没有起到作用

所以想咨询下,**是不是查出来的时候返回的实体类已经自动将为null的字段给忽略掉了?**

或者有什么思路可以实现我上述的要求吗?

**Comment by Stars-One** [comment]
好的,感谢回复
