### ISSUE TITLE
Getting the last record of a table

### ISSUE THREAD

**Issue by ashokgelal** [vincentlauvlwj/Ktorm#34]
Sorry I couldn't find this in the documentation. Is there a built-in efficient way to retrieve the last record from a table without loading all the rows and calling `.lastOrNull()` on it?

**Comment by vincentlauvlwj** [comment]
There is a `lastOrNull` function, but this function loads all the rows from the table, eg: 

```kotlin
val last = Departments.asSequence().lastOrNull()
```

Generated SQL: 

```sql
select ... 
from t_department 
```

It could be intolerable for performance reasons. Therefore, the recommended way to get the last record of a table is to use `sortedByDescending` and `firstOrNull`: 

```kotlin
val last = Departments.asSequence().sortedByDescending { it.id }.firstOrNull()
```

If the MySQL dialect is enabled, the generated SQL would be: 

```sql
select ... 
from t_department 
order by t_department.id desc 
limit 0, 1 
```

Note that the `firstOrNull` function generates a SQL with paging params of `0, 1` (offset 0 limit 1), this **requires a dialect supporting pagination is enabled**, otherwise we'll still load all records in the table to ensure the function just works.

**Comment by ashokgelal** [comment]
Thanks! I knew about `limit` but didn't realize that `firstOrNull` uses `limit` internally. 

In my case, I got it resolved  in a different way. My table has an incrementing numeric `batch` column. I took the advantage of its presence and ran the query like so to get what I wanted:

`Departments.asSequenceWithoutReferences().aggregateColumns { max(it.batch) }`

Do you see any problem doing it this way?

**Comment by vincentlauvlwj** [comment]
It's OK, but the performance could be better. 

To get the last record in your way, you have to find the max `batch` first, then use the max value to find the record you want. In this way, two SQLs are executed: 

```kotlin
// select max(batch) from department
val maxBatch = Departments.maxBy { it.batch }
// select * from department where batch = :maxBatch
val dept = Departments.findOne { it.batch eq maxBatch }
```

But if you use `sortedByDesending` and `firstOrNull`, only one SQL would be executed: 

```kotlin
// select * from department order by batch desc limit 0, 1
val dept = Departments.asSequence().sortedByDescending { it.batch }.firstOrNull()
```

**Comment by ashokgelal** [comment]
That makes sense. However, I've decided to stay with `max` for now as I only need to run this query once in a while so I'm not too worried about making an extra query. Since this is part of a web framework that I'm working on, I don't want to force people to install an extra dependency or configured a dialect.

Also on a side not, since `firstOrNull()` actually uses `limit` when a dialect is enabled, why not make the same for `lastOrNull()` as well to make it consistent. Otherwise, if I had known that `firstOrNull()` uses `limit` when available, I'd have assumed `lastOrNull()` sort of does the same thing.
