### ISSUE TITLE
Column sizes for supporting migrations

### ISSUE THREAD

**Issue by ashokgelal** [vincentlauvlwj/Ktorm#35]
I'm writing some migration scripts where I plan to migrate a Ktorm table by doing something like this:
`migrator.migrate(Departments)`

I was thinking of looping through the columns of the table and then building a CREATE query and then executing it. But, alas, I ran into a big blocker: when declaring fields for a table there is no way to set the size of a field such as for `varchar`. You cannot set other metadata as well such as a default value.

Is there anyway I can attach metadata to a field. If not, are you willing to modify the declaring functions to accept a metadata map?

**Comment by vincentlauvlwj** [comment]
Actually, I've been thinking about the migration support but I don't have a good solution. Happy to know that you are trying to implement it by yourself. Maybe I can get some ideas from your practice. 

As my suggestion, you can create an open class `MigratingTable` extending from `Table`. This is the base class of all your table objects. There are some additional members in this class: 

1. A `metadataMap` property (typed of `HashMap`) that associates the column names and their metadata.
2. A member extension function named `size` for `ColumnRegistration<String>` that saves the registered column's size to `metadataMap`. 
3. Any other extension functions similar to `size`.

```kotlin
open class MigratingTable<E : Entity<E>>(
    tableName: String,
    alias: String? = null,
    entityClass: KClass<E>? = null
) : Table<E>(tableName, alias, entityClass) {

    data class ColumnMetadata(val size: Int? = null, val defaultValue: String? = null)

    val metadataMap = HashMap<String, ColumnMetadata>()

    fun ColumnRegistration<String>.size(size: Int): ColumnRegistration<String> {
        val column = this.getColumn()

        val metadata = metadataMap[column.name]
        if (metadata == null) {
            metadataMap[column.name] = ColumnMetadata(size = size)
        } else {
            metadataMap[column.name] = metadata.copy(size = size)
        }

        return this
    }
}
```

In this way, you can define your table objects based on `MigratingTable` and configure the metadata of your columns: 

```kotlin
object Departments : MigratingTable<Nothing>("t_department") {
    val id by int("id").primaryKey()
    val name by varchar("name").size(16)
    val location by varchar("location").size(256)
}
```

Hope this might help you.

**Comment by ashokgelal** [comment]
That might get the job done. Also aligns to pretty much what I was planning to do. Thank you!
