### ISSUE TITLE
creating an alias with the AS operator

### ISSUE THREAD

**Issue by schmeic** [vincentlauvlwj/Ktorm#37]
How would I do something like this:
`SELECT id, body, MATCH (body)  AGAINST ('mysql tutorial' IN BOOLEAN MODE)
    AS score FROM articles  HAVING score > 0 ORDER BY score DESC;`

1. How do I create an alias with AS?
2. How can I use that alias in a HAVING / ORDER BY clause?

**Comment by vincentlauvlwj** [comment]
Try this: 

```kotlin
val score = match(Articles.body).against("mysql tutorial", SearchModifier.IN_BOOLEAN_MODE).cast(FloatSqlType)

val query = Articles
    .select(Articles.id, Articles.body, score)
    .having { score greater 0F }
    .orderBy(score.desc())
```

**Comment by vincentlauvlwj** [comment]
> Also, what would be the best way to include all of the columns from one table, plus something like this _score_ calculation without having to explicitly list each column? I'd like to be able to do something like this:
> 
> > select(Articles.columns, score)

You can use the plus operator for collections: 

```kotlin
select(Articles.columns + score)
```

**Comment by vincentlauvlwj** [comment]
> That doesn't work, the match against sql is used in both the having and order by clauses. Like this:
> 
> `having (match (articles.body) against (? in boolean mode)) > ? order by match (articles.body) against (? in boolean mode)`
> 
> and there is no `AS score` in the SELECT part of the sql.

Actually, the `AS` operator is currently not supported. 

Thanks for your feedback. I'm working on it.

**Comment by vincentlauvlwj** [comment]
Ktorm 2.6 released. Now, we can assign aliases to the selected columns of a query and use them in subsequent clauses such as `group by` and `having`, just like the `as` keyword in SQL. Here is an example. This query selects departments whose average salary is greater than 100, then returns the average salaries along with their department’s IDs.

```kotlin
val deptId = Employees.departmentId.aliased("dept_id")
val salaryAvg = avg(Employees.salary).aliased("salary_avg")

Employees
    .select(deptId, salaryAvg)
    .groupBy(deptId)
    .having { salaryAvg greater 100.0 }
    .forEach { row ->
        println("${row[deptId]}:${row[salaryAvg]}")
    }
```

Generated SQL:

```sql
select t_employee.department_id as dept_id, avg(t_employee.salary) as salary_avg 
from t_employee 
group by dept_id 
having salary_avg > ?
```
