### ISSUE TITLE
Quering/Updating/Inserting extra columns despite of field mappings

### ISSUE THREAD

**Issue by ashokgelal** [vincentlauvlwj/Ktorm#38]
If I have a table like following:

```kotlin
object Departments : Table<Nothing>("t_department") {
    val id by int("id").primaryKey()
    val name by varchar("name"))
    val location by varchar("location")
}
```

But let's say I've an extra column in table `t_department` called `created_at` (doesn't matter the sql type), is it possible to load all the columns while querying/inserting/updating a record in the table? 

This is useful to me, because as from a framework author, I could provide a base table objects (like `Departments`) in the above example, and based on whether a user has added extra columns or not in the table, (like `created_at`), I could set the value automatically. Something along the lines of:

```
Departments.insertAndGenerateKey {
            it.name to "IT"
           it.location to "New York"
           it.get("created_at")?.to(LocalDateTime.now())
        }
```

I understand that it kind of breaks the static type advantage that Ktorm provides but this is so much useful both for a framework author and the users. I've plenty of other examples where this would create it even more delightful experience for the users.

**Comment by vincentlauvlwj** [comment]
As you said, it breaks the static type advantage that Ktorm provides, so I prefer not to implement it right now. 

Here is my suggestion for your case. You can provide a base class for your table `t_department`, in which some required columns and an optional column `createdAt` are defined. The optional column is an `open val` with a default value `null`, that means it doesn't exist. 

```kotlin
open class BaseDepartments : Table<Nothing>("t_department") {
    val id by int("id").primaryKey()
    val name by varchar("name")
    val location by varchar("location")
    open val createdAt: Column<LocalDateTime>? = null
}
```

Write your function that inserts a record to the specific table: 

```kotlin
fun saveDepartment(tableObject: BaseDepartments = BaseDepartments()) {
    tableObject.insert {
        it.name to "IT"
        it.location to "New York"
        it.createdAt?.to(LocalDateTime.now())
    }
}
```

Now, if the user just calls `saveDepartment()`, the column `createdAt` will be ignored. 

And if the extra column exists, the user should provide his/her custom table object when calling `saveDepartment`: 

```kotlin
object CustomDepartments : BaseDepartments() {
    override val createdAt by datetime("created_at")
}

saveDepartment(CustomDepartments)
```

Hope this might help you.
