### ISSUE TITLE
doCreateEntity withReferences

### ISSUE THREAD

**Issue by schmeic** [vincentlauvlwj/Ktorm#40]
Just saw the new functionality in 2.5:
https://ktorm.liuwj.me/en/define-entities-as-any-kind-of-classes.html

Creating an entity data class seems pretty straightforward, but how should the _withReferences_ parameter be used?

**Comment by vincentlauvlwj** [comment]
It's just a flag indicating whether `createEntity` or `createEntityWithoutReferences` is called. You can find the code here: https://github.com/vincentlauvlwj/Ktorm/blob/master/ktorm-core/src/main/kotlin/me/liuwj/ktorm/schema/BaseTable.kt#L313-L359

`Table` uses this flag to determine if the referenced entity object should be obtained at the same time. The code is here: https://github.com/vincentlauvlwj/Ktorm/blob/master/ktorm-core/src/main/kotlin/me/liuwj/ktorm/schema/Table.kt#L142-L150

If you define your table objects extending from `BaseTable` directly, you can ignore it in most cases, unless you are creating your own binding mechanisms and need to known which function is currently called by users.

**Comment by schmeic** [comment]
Thanks for the info!
