### ISSUE TITLE
Ktorm 'Contains' aggregate

### ISSUE THREAD

**Issue by halimpuckjava** [vincentlauvlwj/Ktorm#42]
hi

when i we want to indicate if string contains an other string use contains method, how ktorm resolve this

**Comment by vincentlauvlwj** [comment]
What's your use case? Could you explain it more detailed?

**Comment by halimpuckjava** [comment]
for exemple:
in sql: select * from table where column-name like '%value%'
with ktorm: table.assequnce().filter { column-name like value } but not work like sql

**Comment by vincentlauvlwj** [comment]
You might have forgetten the `%` symbols. Try this: 

```kotlin
Employees.asSequence().filter { it.name like "%vince%" }
```

**Comment by halimpuckjava** [comment]
thanks, 
yes i don't use % because i expected the 'like' operator do that automaticaly

**Comment by vincentlauvlwj** [comment]
If you want to automate that, write an extension function like: 

```kotlin
fun ColumnDeclaring<String>.contains(argument: String) = this like "%$argument%"
```

Then you can do this: 

```kotlin
Employees.asSequence().filter { it.name.contains("vince") }
```
