### ISSUE TITLE
mariadb timestamp issue

### ISSUE THREAD

**Issue by schmeic** [vincentlauvlwj/Ktorm#43]
When trying to update a timestamp column using an entity with type Instant, the timestamp value looks something like: "2019-09-05T00:00:56.287169Z".
Looking at the logged SQL, everything looks fine (no errors), but the db is not updated. 

Manually running the sql shows an error like: 
"Incorrect datetime value: '2019-09-05T00:00:56.287169Z' for column..." (but the column has type "timestamp")

Shouldn't ktorm report an error when the query fails? I found that if I remove the 'Z' from the end of the value, the query works. What is the recommended way to correctly format a timestamp value from an Instant?

UPDATE: I just tried using a datetime/LocalDateTime in ktorm (even though the db column is still a timestamp) and the value doesn't have the Z at the end, so it works when I run it manually. But for some reason, the flushChanges() is not working even though I am getting the entity from the findOne() method.

**Comment by vincentlauvlwj** [comment]
Show me your code and the SQL used to create the table?

**Comment by schmeic** [comment]
The code is like this:
`val expiresAtVal = Instant.now().plus(Duration.ofDays(1))
var authSession = findOne { userId eq userIdVal }

        if (authSession != null) {
            authSession.expiresAt = expiresAtVal
            authSession.flushChanges()
        } else { ...`

**Comment by vincentlauvlwj** [comment]
Also show me the table object and entity definition?

**Comment by schmeic** [comment]
```
interface AuthSession : Entity<AuthSession> {
    companion object : Entity.Factory<AuthSession>()

    val authSessionId: Int
    val user: User
    var expiresAt: Instant
}
```

**Comment by schmeic** [comment]
```object AuthSessions : Table<AuthSession>("auth_session") {
    private val authSessionId by int("auth_session_id")
        .primaryKey().bindTo { it.authSessionId }

    private val userId by int("user_id").references(Users) { it.user }
    private val expiresAt by timestamp("expires_at").bindTo { it.expiresAt }
...
}```

**Comment by schmeic** [comment]
Not sure if it matters, but I'm using MariaDB 10.2.26.

**Comment by vincentlauvlwj** [comment]
Seems it's not Ktorm's problem. Check your logic of the code or the MariaDB's environments.

**Comment by schmeic** [comment]
Were you unable to reproduce the "Incorrect datetime value: '2019-09-05T00:00:56.287169Z' for column..." error? You should be able to do that just using the mysql cli. Shouldn't ktorm be throwing sql exceptions?

**Comment by vincentlauvlwj** [comment]
Ktorm doesn't format `Instant` values to strings like `2019-09-05T00:00:56.287169Z`. Instead, we use prepared statements to pass SQL arguments to databases. That's different from executing such a SQL using the MySQL cli. 

The datetime value with a `Z` character you memtioned was printed just using the `toString` method of `Instant`, which is nothing to do with Ktorm. Actually, Ktorm transforms `Instant` values to timestamps and pass them to prepated statements. You can find the code here: https://github.com/vincentlauvlwj/Ktorm/blob/master/ktorm-core/src/main/kotlin/me/liuwj/ktorm/schema/SqlTypes.kt#L342-L360

Therefore, it's not possible for Ktorm to produce such an exception like `Incorrect datetime value...`. Check your code or database environment again.

**Comment by schmeic** [comment]
Actually, it looks a bigger problem - no writes to the db work using entities (I haven't tried DSL yet). Things used to work. I did recently upgrade to Ktorm 2.5 and Kotlin 1.3.50. Is that the Kotlin version you're using? Any ideas on how to debug this?
