### ISSUE TITLE
Joining a last activity record

### ISSUE THREAD

**Issue by ashokgelal** [vincentlauvlwj/Ktorm#45]
I've following two entities where I'm trying to get the latest activity for an employee:

```kotlin
interface Activity : Entity<Activity> {
    val id: Long
    val desc: String
    val employee: Employee
    val createdAt: LocalDateTime?
    companion object : Entity.Factory<Activity>()
}

interface Employee : Entity<Employee> {
    var id: Long
    var name: String
    
    val latestActivity: Activity?
        get() {
            var activity = this["latestActivity"]
            if (activity == null) {
                activity = Activities.asSequenceWithoutReferences().sortedByDescending { it.createdAt }
                    .filter { it.employeeId eq id }.firstOrNull()
                this["latestActivity"] = activity
            }
            return activity as? Activity
        }
    companion object : Entity.Factory<Employee>()
}
```

This all works great but unfortunately for each employee getting the `latestActivity` is an extra query. What's the best way to fetch Employees and have it returned with `latestActivity` joined?

**Comment by vincentlauvlwj** [comment]
It could be easier if the `id` in `activity` table is an auto-increment key. 

I tried to write some code. In this way three SQLs are generated: 

```kotlin
// select ... from employee
val employees = Employees.findAll()

val employeeIds = employees.map { it.id }

// select activity.employee_id, max(activity.id)
// from activity
// where activity.employee_id in (?, ?, ...)
// group by activity.employee_id
val latestActivityIds = Activities.asSequence()
    .filter { it.employeeId inList employeeIds }
    .groupingBy { it.employeeId }
    .eachMaxBy { it.id }

// select ... from activity where activity.id in (?, ?, ...)
val activities = Activities.findMapByIds(latestActivityIds.values.filterNotNull())

for (employee in employees) {
    val activityId = latestActivityIds[employee.id] ?: continue
    employee.latestActivity = activities[activityId]
}
```

**Comment by vincentlauvlwj** [comment]
I also tried to use a native SQL. In this way, only one query is executed: 

```kotlin
val employees = useConnection { conn ->
    val sql = """
        select emp.id as emp_id, emp.name as emp_name, act.id as act_id, act.desc as act_desc, act.created_at as act_time
        from employee emp left join (
            select a.id, a.employee_id, a.desc, a.created_at
            from activity a
            where a.id = (
                select max(b.id)
                from activity b
                where b.employee_id = a.employee_id
            )
        ) act on emp.id = act.employee_id;
    """.trimIndent()

    conn.prepareStatement(sql).use { statement ->
        statement.executeQuery().use { rs ->
            rs.iterable().map { row ->
                Employee {
                    id = row.getLong("emp_id")
                    name = row.getString("emp_name")
                    latestActivity = Activity {
                        id = row.getLong("act_id")
                        desc = row.getString("act_desc")
                        createdAt = row.getTimestamp("act_time")?.toLocalDateTime()
                    }
                }
            }
        }
    }
}
```

**Comment by ashokgelal** [comment]
I should have mentioned that the IDs are auto incrementing primary keys. The first solution is a good solution for someone like me who isn't very comfortable writing raw queries.

I was doing some reading on how people solve this problem and came across this article that talks about how this could be achieved using just a single query and keeping it efficient as well using `subqueries`. 

Although this article is written for PHP (and for Laravel framework), I think this could be added in ktorm as well. I found other examples online where subqueries make writing complex queries very intuitive and keeps it within ORM boundary. 

Here is the article (you don't have to read the whole article if you don't want to, you can stop when it starts talking about macros): https://reinink.ca/articles/dynamic-relationships-in-laravel-using-subqueries

**Comment by vincentlauvlwj** [comment]
Thank you. This is a good article. In fact, I also have a plan to support subqueries. The final usage should be similar to that in this article.

**Comment by ashokgelal** [comment]
Great! I would be very happy to test it out on a real database once ready. Any idea about when it might be available?
