### ISSUE TITLE
多数据源切换的一个建议.

### ISSUE THREAD

**Issue by JsonSong89** [vincentlauvlwj/Ktorm#47]
ktorm是支持多数据源的,但是感觉用起来有点不太方便.
比如我一直用的是单一数据源(primary)
但有一天我需要加一个数据源,访问一个配置数据库(second).
结果是我原来的所有primary的dao方法都受到影响了,
现在只要访问一次second,我得将primary invoke一次,不然primary对应的方法就会使second数据源.

有两个想法:
1.可以给Database设置生效的aspect,Database只对这个aspect下面的table objects生效
2.可以为table objects设置Database,优先使用自己的db,而不是全部使用Database.global

**Comment by vincentlauvlwj** [comment]
谢谢，类似的建议 #41

**Comment by try520** [comment]
为什么不能一个数据库是一个对象，对象下该数据库的表，然后是该表的access
类似 db1.tableName.findAll()，db2.tableName.findAll() 不是更清晰么

**Comment by vincentlauvlwj** [comment]
@try520 

谢谢，我正在做这个改进，现在已经完成了，等完善文档之后就会发布 2.7 版本，有兴趣的话可以先看看 [rm-global-database-object](https://github.com/vincentlauvlwj/Ktorm/tree/rm-global-database-object) 分支里面的测试用例，下面是重构之后的使用示例：

![Ktorm Example](https://raw.githubusercontent.com/vincentlauvlwj/Ktorm/rm-global-database-object/docs/source/images/ktorm-example.png)

**Comment by JsonSong89** [comment]
@vincentlauvlwj 
感谢作者的付出.

是完全移除global db吗?
但是感觉如果是单数据源,之前的方式还是很方便的.
如果按照2.7的话,又得每次都写一点样板代码了

**Comment by vincentlauvlwj** [comment]
使用到 global db 的地方不会直接移除，会标记为 `@Deprecated`

至于样板代码，现在的改变只是把 `Employees.select(..)` 改成 `db.from(Employees).select(..)`，把 `Employees.asSequence()` 改成 `db.sequenceOf(Employees)`，我感觉并没有太大影响

**Comment by JsonSong89** [comment]
主要是db需要引入下,如果是用spring注入的,还得再从beanFactory拿出来.

**Comment by vincentlauvlwj** [comment]
那也仅仅是一个 `@Autowired` 而已，对于使用 Spring 的人来说，这不是正常操作吗 :grinning:

从这段时间的经验看来，在框架内部保存一个全局的数据库对象，除了 API 设计方便一点点之外，真的是弊大于利，多数据源切换不方便是一个，还有因为使用 `ThreadLocal` 给代码引入了一个隐式的变量，即不直观也容易造成误解

**Comment by JsonSong89** [comment]
嗯 不直观倒是真的,毕竟全局变量本身就容易出问题.也带来很多复杂度.
我之前是想到mybatis也是用的全局的,不过这里到没必要类比.
用db打头也没什么.

**Comment by vincentlauvlwj** [comment]
Ktorm 2.7 废弃了全局对象和 thread local，现已发布，请参见 https://ktorm.liuwj.me/zh-cn/about-deprecating-database-global.html
