### ISSUE TITLE
SQLite Datetime column class cast exception 

### ISSUE THREAD

**Issue by ashokgelal** [vincentlauvlwj/Ktorm#51]
I've a simple entity that has a `hired_at` datetime type column. I can insert a new record successfully but trying to fetch it back throws a casting exception:

`java.base/java.lang.Long cannot be cast to java.sql/java.sql.Date`

This only happens with a SQLite connection and not with MySQL connection. Here is a repro repo: https://github.com/ashokgelal/ktorm-sqlite-repro
You need to copy `ktrom_repro.sqlite` file to your home folder.

**Comment by vincentlauvlwj** [comment]
Most SQL database engines uses static, rigid typing. But SQLite uses a more general dynamic type system.

SQLite only supports five data types, they are NULL, INTEGER, REAL, TEXT, BLOB. There is not a data type set aside for storing dates and/or times. Dates and times are stored stored as TEXT, REAL, or INTEGER values: 

 - TEXT as ISO8601 strings ("YYYY-MM-DD HH:MM:SS.SSS").
 - REAL as Julian day numbers, the number of days since noon in Greenwich on November 24, 4714 B.C. according to the proleptic Gregorian calendar.
 - INTEGER as Unix Time, the number of seconds since 1970-01-01 00:00:00 UTC.

More details can be found at: https://www.sqlite.org/datatype3.html

**Comment by vincentlauvlwj** [comment]
In your case, you should not use the `datetime` function to store datetimes to SQLite. If you want to save datetimes as integers, you can write a custom implementation of `SqlType`: 

```kotlin
fun <E : Any> BaseTable<E>.datetimeAsInteger(name: String): BaseTable<E>.ColumnRegistration<LocalDateTime> {
    return registerColumn(name, DateTimeAsIntegerSqlType)
}

object DateTimeAsIntegerSqlType : SqlType<LocalDateTime>(Types.INTEGER, "integer") {
    override fun doSetParameter(ps: PreparedStatement, index: Int, parameter: LocalDateTime) {
        val seconds = parameter.atZone(ZoneId.systemDefault()).toEpochSecond()
        ps.setLong(index, seconds)
    }

    override fun doGetResult(rs: ResultSet, index: Int): LocalDateTime? {
        val seconds = rs.getLong(index)
        return Instant.ofEpochSecond(seconds).atZone(ZoneId.systemDefault()).toLocalDateTime()
    }
}
```

Then define the `hireAt` column using this `datetimeAsInteger` function: 

```kotlin
object Employees : Table<Employee>("employees") {
    val id by int("id").primaryKey().bindTo { it.id }
    val name by varchar("name").bindTo { it.name }
    val hiredAt by datetimeAsInteger("hired_at").bindTo { it.hiredAt }
}
```

**Comment by ashokgelal** [comment]
I didn't know that. Thanks.

Any suggestion on a good way to make the conversion "automatic" without forcing users to change the column type when they switch from, say, MySQL, to SQLite?

**Comment by ashokgelal** [comment]
Just saw your last reply. That works but then I have to force users to change their column type everytime they switch from one db provider to SQLite.

You might be wondering what is my use case. Well, I want to run unit tests on a sqlite database and real app with a full MySQL server. Ideally with other ORMs I do with a in-memory sqlite database. (On a side note, I could never get sqlite in-memory database to work with Ktorm.)

**Comment by vincentlauvlwj** [comment]
Every database engine has its special features. It is difficult to find a perfect way to handle their differences. In you case, for compatibility reasons, you can always define your datetime columns using `datetimeAsInteger`, that works both in SQLite and MySQL. 

BTW, [SQLiteTest](https://github.com/vincentlauvlwj/Ktorm/blob/master/ktorm-support-sqlite/src/test/kotlin/me/liuwj/ktorm/support/sqlite/SQLiteTest.kt) is an example using SQLite in memory mode with Ktorm.

**Comment by vincentlauvlwj** [comment]
And if you are using SQLite just for running unit tests, [testcontainers](https://www.testcontainers.org/) might be a better choice to do that.
