### ISSUE TITLE
Array support

### ISSUE THREAD

**Issue by ddk9499** [vincentlauvlwj/Ktorm#55]
Hey. Is there any solution to store array data type via Ktorm?

**Comment by vincentlauvlwj** [comment]
You can write your own support for array data type. For example: 

```kotlin
fun <E : Any> BaseTable<E>.array(name: String): BaseTable<E>.ColumnRegistration<java.sql.Array> {
    return registerColumn(name, ArraySqlType)
}

object ArraySqlType : SqlType<java.sql.Array>(Types.ARRAY, "array") {

    override fun doSetParameter(ps: PreparedStatement, index: Int, parameter: Array) {
        ps.setArray(index, parameter)
    }

    override fun doGetResult(rs: ResultSet, index: Int): Array? {
        return rs.getArray(index)
    }
}
```

Then you can use this `array` extension function to define your array columns: 

```kotlin
object Foo : Table<Nothing>("foo") {
    val bar by array("bar")
}
```

**Comment by ddk9499** [comment]
thank you!

**Comment by geertijewski** [comment]
```kt
fun <E : Any> BaseTable<E>.array(name: String): Column<Array> {
    return registerColumn(name, ArraySqlType)
}

object ArraySqlType : SqlType<java.sql.Array>(Types.ARRAY, "array") {

    override fun doSetParameter(ps: PreparedStatement, index: Int, parameter: java.sql.Array) {
        ps.setArray(index, parameter)
    }

    override fun doGetResult(rs: ResultSet, index: Int): java.sql.Array? {
        return rs.getArray(index)
    }
}
```

is the corrected code as of today

**Comment by LIMPIX31** [comment]
> > ```kotlin
> > fun <E : Any> BaseTable<E>.array(name: String): Column<Array> {
> >     return registerColumn(name, ArraySqlType)
> > }
> > 
> > object ArraySqlType : SqlType<java.sql.Array>(Types.ARRAY, "array") {
> > 
> >     override fun doSetParameter(ps: PreparedStatement, index: Int, parameter: java.sql.Array) {
> >         ps.setArray(index, parameter)
> >     }
> > 
> >     override fun doGetResult(rs: ResultSet, index: Int): java.sql.Array? {
> >         return rs.getArray(index)
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > is the corrected code as of today
> 
> Can I make something like this, but with `LongArray`? Help me plz.

Ник какой-то знакомый

**Comment by LIMPIX31** [comment]
> ```kotlin
> fun <E : Any> BaseTable<E>.array(name: String): Column<Array> {
>     return registerColumn(name, ArraySqlType)
> }
> 
> object ArraySqlType : SqlType<java.sql.Array>(Types.ARRAY, "array") {
> 
>     override fun doSetParameter(ps: PreparedStatement, index: Int, parameter: java.sql.Array) {
>         ps.setArray(index, parameter)
>     }
> 
>     override fun doGetResult(rs: ResultSet, index: Int): java.sql.Array? {
>         return rs.getArray(index)
>     }
> }
> ```
> 
> is the corrected code as of today

How can I check if there is an element in the array in the `where` block?

**Comment by ChA0S-f4me** [comment]
> @ChA0S-f4me 
> 
> Ник какой-то знакомый

Да, есть такое)) Я там на твоём патче паутину с мираи сделал, кста))
