### ISSUE TITLE
How to use entities with many to many relations ?

### ISSUE THREAD

**Issue by sliya** [vincentlauvlwj/Ktorm#56]
Let's say I have a table Recipe(id, name) and another Tag(id, label). Each recipe may have several tags and each tag can be used for several recipes, so i create a table TagRecipe(idTag, idRecipe).
How can I declare a Recipe entity having a list of tags ? This is what I have for now, but I don't know how to populate Recipe.tags :
```kotlin
interface Recipe: Entity<Recipe>{
    val id: Int
    val name: String
    val tags: List<Tag>
}

object Recipes: Table<Recipe>("recipes"){
    val id by int("id").primaryKey().bindTo { it.id }
    val name by varchar("name").bindTo { it.name }
}

interface Tag: Entity<Tag> {
    val id: Int
    val label: String
}

object Tags: Table<Tag>("tags"){
    val id by int("id").primaryKey().bindTo { it.id }
    val label by varchar("name").bindTo { it.label }
}

interface TagRecipe: Entity<TagRecipe>{
    val idTag: Int
    val idRecipe: Int
}

object TagRecipes: Table<TagRecipe>("tags_recipes"){
    val idTag by int ("idTag").primaryKey().bindTo{it.idTag}
    val idRecipe by int ("idRecipe").primaryKey().bindTo{it.idRecipe}
}
```

**Comment by JoonasC** [comment]
AFAIK, Ktorm doesn't currently support many to many relations out of the box.
I usually work around this by having a function, which returns a list through a query.
So in your case it would be:
interface Recipe: Entity<Recipe>{
    val id: Int
    val name: String
    fun getTags(): List<Tag> = TagRecipes.findList { it.idRecipe eq id }
}

**Comment by JoonasC** [comment]
On another note, you might want to change your `TagRecipes` joining table schema to use references (foreign keys), instead of manually setting the ids in your code. https://ktorm.liuwj.me/en/entities-and-column-binding.html#Column-Binding

**Comment by sliya** [comment]
Ok, thanks

**Comment by vincentlauvlwj** [comment]
Comparing to writing a function, I'd prefer using a property with a custom getter: 

```kotlin
interface Recipe: Entity<Recipe>{
    val id: Int
    val name: String
    val tags get() = TagRecipes.findList { it.idRecipe eq id }
}
```

**Comment by DavidGrinberg** [comment]
Now that `findList` is deprecated in favor of `database.sequenceOf()`, what is the suggested way to do this?

**Comment by vincentlauvlwj** [comment]
@DavidGrinberg Here is our discussions about this problem https://github.com/vincentlauvlwj/Ktorm/issues/73
