### ISSUE TITLE
Add a new SQL type to handle UUID type in database

### ISSUE THREAD

**Issue by DPorcheron** [vincentlauvlwj/Ktorm#57]
Hello.

First of all, thank you for this awesome Kotlin ORM framework !

I just wonder if it would be possible to add a new common SQL type for `UUID` type. They are common used in SQL databases like PostgreSQL and it would be a simple addition in the code base.

Maybe we could do something like that :
```
fun <E : Entity<E>> BaseTable<E>.uuid(name: String): BaseTable<E>.ColumnRegistration<UUID> {
    return registerColumn(name, UuidSqlType)
}

object UuidSqlType : SqlType<UUID>(Types.OTHER, "uuid") {

    override fun doSetParameter(ps: PreparedStatement, index: Int, parameter: UUID) {
        ps.setObject(index, parameter)
    }

    override fun doGetResult(rs: ResultSet, index: Int): UUID {
        return rs.getObject(index) as UUID
    }
}
```
Thanks in advance for your response.

**Comment by vincentlauvlwj** [comment]
Thank you for your suggestion. I will add it to the next release.

**Comment by shavz** [comment]
Hi @vincentlauvlwj would be interested in this as well. Do you know when this would be added?

**Comment by vincentlauvlwj** [comment]
Added to version 2.7
