### ISSUE TITLE
Add something to easily handle the mapping of Enum in database

### ISSUE THREAD

**Issue by DPorcheron** [vincentlauvlwj/Ktorm#58]
Hello.

I wonder if it would be possible to add something to easily handle mapping of `Enum` type in database ? A mapper which map an `Enum` Kotlin field into a `VARCHAR` database field.

Maybe adding a specific `SqlType` for the enums ?

What do you think about that ?

**Comment by vincentlauvlwj** [comment]
We can add a `SqlType` implementation to handle enums: 

```kotlin
fun <E : Any, C : Enum<C>> BaseTable<E>.enum(name: String, typeRef: TypeReference<C>): BaseTable<E>.ColumnRegistration<C> {
    return registerColumn(name, EnumSqlType(typeRef.referencedType as Class<C>))
}

class EnumSqlType<C : Enum<C>>(val enumClass: Class<C>) : SqlType<C>(Types.VARCHAR, "varchar") {
    private val valueOf = enumClass.getDeclaredMethod("valueOf", String::class.java)

    override fun doSetParameter(ps: PreparedStatement, index: Int, parameter: C) {
        ps.setString(index, parameter.name)
    }

    override fun doGetResult(rs: ResultSet, index: Int): C? {
        return rs.getString(index)?.takeIf { it.isNotBlank() }?.let { enumClass.cast(valueOf(null, it)) }
    }
}
```

Usage: 

```kotlin
object Employees : Table<Nothing>("t_employee") {
    // ...
    val sex by enum("sex", typeRef<Sex>)
}
```

**Comment by ganatrat** [comment]
Any plan to release this any time soon? I am using version 2.6 and it's not available.

**Comment by vincentlauvlwj** [comment]
I've added it to version 2.7, which might be released next month. 

If you need to use it right now, you can copy the codes above to your project temporarily.

**Comment by jiaojing** [comment]
数据库里的enum，默认是用的name，这个感觉不是很友好。我们自己定义了一个，用的tinyInt。

`
interface HasCodeEnum {
    val code: Int
}

inline fun <reified T : HasCodeEnum> Int?.ofEnum(): T? {
    if (this == null) return null
    val enums = T::class.java.enumConstants
    return enums.firstOrNull { it.code == this }
}

data class EnumSqlType<T : HasCodeEnum>(
        val enumType: KClass<T>
) : SqlType<T>(Types.TINYINT, typeName = "enum") {

    override fun doSetParameter(
            ps: PreparedStatement,
            index: Int,
            parameter: T ) {

        ps.setInt(index, parameter.code)
    }

    override fun doGetResult(
            rs: ResultSet,
            index: Int ): T? {

        val code = rs.getInt(index)
        val enums = enumType.java.enumConstants
        return enums.firstOrNull { it.code == code }
    }
}
`

**Comment by vincentlauvlwj** [comment]
@jiaojing Great.

**Comment by vincentlauvlwj** [comment]
Ktorm 2.7 is released.
