### ISSUE TITLE
定义Entity时能否增加自定义逻辑

### ISSUE THREAD

**Issue by gongxuanzhang** [vincentlauvlwj/Ktorm#587]
数据库表和实体表结构不同，希望直接通过映射进行自定义转换，下例用一个伪代码阐述

```kotlin
object Departments : Table<Department>("t_department") {
  //   不存在的map函数, 伪代码
    val name = varchar("name").map { it.value == "张三" }.bindTo { it.name }
}

interface Department : Entity<Department> {
    var name:Boolean 
}
```

在非Web开发时，轻量级使用数据库，并不希望定义许多POJO,希望class的语义和期望符合。
理论上可以通过修改表结构解决，现在的需求需要查information_schema库，结构不能自己定义。
同时如果需要为用户提供视图时此功能也需要。

我参阅了 [列绑定文档](https://www.ktorm.org/zh-cn/entities-and-column-binding.html#%E5%88%97%E7%BB%91%E5%AE%9A)没有找到此功能，如果已经有此功能麻烦提示我一下文档地址。

感谢

**Comment by vincentlauvlwj** [comment]
可以了解下 [transform](https://www.ktorm.org/api-docs/ktorm-core/org.ktorm.schema/-base-table/transform.html) 函数

**Comment by gongxuanzhang** [comment]
十分感谢，这就是我想要的
