### ISSUE TITLE
升级Kotlin 2.1.0版本KSP编译不成功

### ISSUE THREAD

**Issue by SamiuZhong** [vincentlauvlwj/Ktorm#589]
升级Kotlin 2.1.0版本和KSP 2.1.0-1.0.29版本后，KSP编译不成功。

**Comment by vincentlauvlwj** [comment]
暂时还没有适配过 Kotlin 2.0 以上版本，后面会考虑支持

**Comment by JsonSong89** [comment]
#577  

ksp的2.0版本可以编译啊,你看下我帖子里面的,版本改成2直接就成功了,其他都没动

**Comment by SamiuZhong** [comment]
> #577
> 
> ksp的2.0版本可以编译啊,你看下我帖子里面的,版本改成2直接就成功了,其他都没动

兄弟，我说的是 2.1.0 不是 2.0.0
