### ISSUE TITLE
是否考虑添加调用数据库内置函数（例如 now() ）的支持？

### ISSUE THREAD

**Issue by JuerGenie** [vincentlauvlwj/Ktorm#61]
尝试着在API文档和Issues中寻找了一圈，似乎没有看到类似的内容，不知是否是我没找到。
因此现在在项目中如果需要用到函数或者Custom Function的话，还是要手写sql（然后嫌麻烦自己封装了一个Operator，进行基本的调用语句的拼装）。

如果可以的话，希望能够有类似以下的原生API可供调用：
```kotlin
TemplateTable.asSequence()
    .filter { it.createDate eq call("to_date", "2019/11/10", "yyyy/MM/dd") }
    .toList()
```

**Comment by vincentlauvlwj** [comment]
https://github.com/vincentlauvlwj/Ktorm/issues/25#issuecomment-503386729

这个 issue 里面有提到如何自己增加 SQL 函数的支持，按照这个方法，你可以写一个这样的扩展函数：

```kotlin
fun now(): FunctionExpression<Instant> {
    return FunctionExpression(functionName = "now", arguments = emptyList(), sqlType = InstantSqlType)
}
```

用法：

```kotlin
TemplateTable.asSequence()
    .filter { it.createDate eq now() }
    .toList()
```

**Comment by JuerGenie** [comment]
谢谢👌看起来是我检索的时候用错关键词了，这个方式能够满足需求了。
