### ISSUE TITLE
How can I use different catalog(or schema in jpa) in one datasource

### ISSUE THREAD

**Issue by gimslab** [vincentlauvlwj/Ktorm#62]
Hi, thanks for good ORM. I'm starting to use this greate ORM these days.

How can I use multiple db(or schema, or catalog) name in same datasource like JPA.

for example in JPA
----
@Table(catalog = "sales", name = "product_sales")
----

I browsed all the documentation and tried it in many ways, but it was not successful. I'm using mysql.

**Comment by vincentlauvlwj** [comment]
Catalog is not supported yet. 

But you can configure multiple `Database` instances in an App, see https://ktorm.liuwj.me/en/connect-to-databases.html#Global-Object-amp-Multi-Databases

**Comment by gimslab** [comment]
Thanks for your answer.
