### ISSUE TITLE
limit和orderBy同时使用时候异常

### ISSUE THREAD

**Issue by EasyUseWang** [vincentlauvlwj/Ktorm#67]
limit和orderBy同时使用时，com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'AID'.，代码如下：
var result = staff.innerJoin(department, on = department.aid eq staff.departmentAid)
                .innerJoin(stateStaff, on = stateStaff.id eq staff.stateId)
                .select(staff.phone, staff.name, stateStaff.name)
                .where { staff.aid eq 51 }
                .orderBy(staff.aid.desc())
                .limit(0, 15)
                .map { row -> StaffEntity(row[staff.phone] + "454", row[staff.name], row[stateStaff.name]) }

**Comment by vincentlauvlwj** [comment]
表对象的定义可以提供一下？

**Comment by EasyUseWang** [comment]
package com.yneusoft.demoktorm.dao;
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
import com.yneusoft.demoktorm.model.Staff;
import me.liuwj.ktorm.schema.Table
import me.liuwj.ktorm.schema.boolean
import me.liuwj.ktorm.schema.varchar
import me.liuwj.ktorm.schema.int

/**
 * (Staff)表数据库访问层
 *
 * @author makejava
 * @since 2019-12-17 21:03:24
 */
open class StaffDao(alias: String?) : Table<Nothing> ("Staff", alias) {
    companion object : StaffDao(null)
    override fun aliased(alias: String) = StaffDao(alias)
    
        /**
    * -- 工作人员
    */
    val aid by int("AID").primaryKey()
    /**
    * --FK[Company]【冗余】所属公司A
    */
    val companyAid by int("CompanyAID")
    /**
    * --FK[Department] 部门aid
    */
    val departmentAid by int("DepartmentAID")
    /**
    * --FK[StateStaff]状态id
    */
    val stateId by int("StateID")
    /**
    * --0 表示正式员工 1表示临时工
    */
    val typeId by int("TypeID")
    /**
    * -- 工号
    */
    val code by varchar("Code")
    /**
    * -- 姓名
    */
    val name by varchar("Name")
    /**
    * -- 性别：1男0女
    */
    val sex by boolean("Sex")
    /**
    * -- 电话
    */
    val phone by varchar("Phone")
    /**
    * -- 邮箱
    */
    val email by varchar("Email")
    /**
    * -- 身份证号码:去校验
    */
    val id by varchar("IDCode")
    /**
    * -- 证件照片Code
    */
    val photoFileCode by varchar("PhotoFileCode")
    /**
    * -- 登录密码
    */
    val loginKey by varchar("LoginKey")
    /**
    * --FK[TypeBank] 工资银行id
    */
    val bankId by int("BankID")
    /**
    * -- 工资卡银行开户行
    */
    val bankName by varchar("BankName")
    /**
    * -- 工资卡账号
    */
    val bankCard by varchar("BankCard")
    /**
    * -- 微信小程序OPENID
    */
    val waOpenId by varchar("WaOpenID")
    /**
    * -- 用户在三方平台的唯一标识
    */
    val unionId by varchar("UnionID")
    /**
    * -- 全局编码32位UUID
    */
    val globalCode by varchar("GlobalCode")
    /**
    * -- 推广码
    */
    val referralCode by varchar("ReferralCode")
}
这就是表对象

**Comment by EasyUseWang** [comment]
> 表对象的定义可以提供一下？



> 表对象的定义可以提供一下？
package com.yneusoft.demoktorm.dao;
import com.yneusoft.demoktorm.model.Staff;
import me.liuwj.ktorm.schema.Table
import me.liuwj.ktorm.schema.boolean
import me.liuwj.ktorm.schema.varchar
import me.liuwj.ktorm.schema.int

/**
 * (Staff)表数据库访问层
 *
 * @author makejava
 * @since 2019-12-17 21:03:24
 */
open class StaffDao(alias: String?) : Table<Nothing> ("Staff", alias) {
    companion object : StaffDao(null)
    override fun aliased(alias: String) = StaffDao(alias)
    
        /**
    * -- 工作人员
    */
    val aid by int("AID").primaryKey()
    /**
    * --FK[Company]【冗余】所属公司A
    */
    val companyAid by int("CompanyAID")
    /**
    * --FK[Department] 部门aid
    */
    val departmentAid by int("DepartmentAID")
    /**
    * --FK[StateStaff]状态id
    */
    val stateId by int("StateID")
    /**
    * --0 表示正式员工 1表示临时工
    */
    val typeId by int("TypeID")
    /**
    * -- 工号
    */
    val code by varchar("Code")
    /**
    * -- 姓名
    */
    val name by varchar("Name")
    /**
    * -- 性别：1男0女
    */
    val sex by boolean("Sex")
    /**
    * -- 电话
    */
    val phone by varchar("Phone")
    /**
    * -- 邮箱
    */
    val email by varchar("Email")
    /**
    * -- 身份证号码:去校验
    */
    val id by varchar("IDCode")
    /**
    * -- 证件照片Code
    */
    val photoFileCode by varchar("PhotoFileCode")
    /**
    * -- 登录密码
    */
    val loginKey by varchar("LoginKey")
    /**
    * --FK[TypeBank] 工资银行id
    */
    val bankId by int("BankID")
    /**
    * -- 工资卡银行开户行
    */
    val bankName by varchar("BankName")
    /**
    * -- 工资卡账号
    */
    val bankCard by varchar("BankCard")
    /**
    * -- 微信小程序OPENID
    */
    val waOpenId by varchar("WaOpenID")
    /**
    * -- 用户在三方平台的唯一标识
    */
    val unionId by varchar("UnionID")
    /**
    * -- 全局编码32位UUID
    */
    val globalCode by varchar("GlobalCode")
    /**
    * -- 推广码
    */
    val referralCode by varchar("ReferralCode")
}

**Comment by vincentlauvlwj** [comment]
不好意思，仅凭你提供的这点信息，是没有办法排查问题的

让你提供表对象，并不是真的只要表对象就可以了:joy: 为了方便排查问题，起码你至少要提供：

- 涉及到的所有表的结构（你这里用到了三个表，但是却只提供了一个表对象）
- 表里的关键数据（若涉及到公司机密请注意脱敏）
- 所使用的的 Ktorm 的版本
- 完整的异常栈（划重点）

另外，提醒一下，在贴代码的时候，请注意一下排版哦:smiley:

**Comment by vincentlauvlwj** [comment]
请问问题还存在吗？没有的话我就关闭 issue 了
