### ISSUE TITLE
将tinyint(1)解析为int类型错误

### ISSUE THREAD

**Issue by 641571835** [vincentlauvlwj/Ktorm#71]
![image](https://user-images.githubusercontent.com/45026715/71538147-46866200-2961-11ea-9c4e-6c30a2f904a0.png)
![image](https://user-images.githubusercontent.com/45026715/71538149-4dad7000-2961-11ea-9687-dfe7f4e4371f.png)
![image](https://user-images.githubusercontent.com/45026715/71538156-703f8900-2961-11ea-9c83-cfa912ec4164.png)
jdbc会将结果返回为boolean
这是我用的驱动版本mysql:mysql-connector-java:5.1.48

**Comment by vincentlauvlwj** [comment]
是的，MySQL 的驱动确实会把 tinyint(1) 返回为 boolean

我感到不解的是，既然数据库里面的类型是 tinyint(1)，你大概率是把这个字段当成布尔值来用的，为什么在 Ktorm 里面定义表对象的时候又定义成 int 呢，为什么不用 boolean 呢：

```kotlin
object AreaToilets : Table<AreaToilet>("T_AREA_TOILET") {
    val smart by boolean("smart").bindTo { it.smart }
}
```

**Comment by 641571835** [comment]
主要是怕这个字段以后还有第三种值,所以我们会用int来代替boolean

**Comment by vincentlauvlwj** [comment]
好，下个版本我会修改一下 `geInt` 函数，如果结果是 `boolean` 的话，自动做一下转换

在此之前，你可以自己定义一个 `tinyint` 扩展函数，绕过这个问题：

```kotlin
fun <E : Any> BaseTable<E>.tinyint(name: String): BaseTable<E>.ColumnRegistration<Int> {
    return registerColumn(name, TinyintSqlType)
}

object TinyintSqlType : SqlType<Int>(Types.TINYINT, "tinyint") {
    override fun doSetParameter(ps: PreparedStatement, index: Int, parameter: Int) {
        ps.setBoolean(index, parameter != 0)
    }

    override fun doGetResult(rs: ResultSet, index: Int): Int? {
        return if (rs.getBoolean(index)) 1 else 0
    }
}
```

用法：

```kotlin
object AreaToilets : Table<AreaToilet>("T_AREA_TOILET") {
    val smart by tinyint("smart").bindTo { it.smart }
}
```

**Comment by 641571835** [comment]
好的谢谢

**Comment by vincentlauvlwj** [comment]
Fixed in Ktorm 2.7
