### ISSUE TITLE
查询中文，失败，查询不到记录

### ISSUE THREAD

**Issue by try520** [vincentlauvlwj/Ktorm#72]
`Database.connect("jdbc:mysql://127.0.0.1:3307/base-frame?charset=utf8mb4&useSSL=false", driver = "com.mysql.cj.jdbc.Driver", user = "root", password = "123456")`

var items2=iframeDict.findList { db.iframeDict.zdValue eq "私有分类" }
items2 查询不到结果，将中文换为英文，查询正常

以下为模型定义：

object iframeDict : Table<iframeDict>("iframe_dict") {
val zdId by int("zd_ID").primaryKey().bindTo { it.zdId }
val zdName by varchar("zd_Name").bindTo { it.zdName }
val zdValue by varchar("zd_value").bindTo { it.zdValue }
val zdLabel by varchar("zd_label").bindTo { it.zdLabel }
val zdType by int("zd_type").bindTo { it.zdType }
val zdSort by int("zd_sort").bindTo { it.zdSort }
val zdParentid by int("zd_ParentID").bindTo { it.zdParentid }
val zdIsparent by int("zd_IsParent").bindTo { it.zdIsparent }
val zdIsshow by int("zd_IsShow").bindTo { it.zdIsshow }
val zdAttr by varchar("zd_Attr").bindTo { it.zdAttr }
}

interface iframeDict : Entity<iframeDict> {
companion object : Entity.Factory<iframeDict>()
val zdId: Int?
val zdName: String?
val zdValue: String?
val zdLabel: String?
val zdType: Int?
val zdSort: Int?
val zdParentid: Int?
val zdIsparent: Int?
val zdIsshow: Int?
val zdAttr: String?
}

**Comment by vincentlauvlwj** [comment]
你说中文换为英文查询正常，请问下你的英文的查询是怎么写的？

另外可以提供一下你表中的测试数据吗？

**Comment by try520** [comment]
--------------
查询条件里有中文 都查不出数据

**Comment by try520** [comment]
var items2=iframeDict.findList { db.iframeDict.zdValue eq "私有分类" } 返回数组 size =0
var items2=db.iframeDict.findList { db.iframeDict.zdValue eq "test" } 返回数组 size >0 
保证查询条件是正确的，数据库中也有记录

**Comment by try520** [comment]
问题应该出在编码上，我的数据库编码为 utf8mb4

**Comment by vincentlauvlwj** [comment]
哦，那应该跟 Ktorm 没有关系？

**Comment by try520** [comment]
不确定 mybatis 正常

**Comment by vincentlauvlwj** [comment]
那你可以提供详细一点的信息？这样子没办法排查

**Comment by try520** [comment]
您那边测试下 select * from xx where  xxx='中文' 能查询出数据吗，我这边查询不到数据 ，就是这么个问题

**Comment by vincentlauvlwj** [comment]
不好意思，我能正常查询，重现不出你的问题
