### ISSUE TITLE
BaseDaoImpl 怎么搞？

### ISSUE THREAD

**Issue by UIdoer** [vincentlauvlwj/Ktorm#74]
https://gitee.com/itdoer/ublog/blob/master/src/main/kotlin/top/rish/core/dao/BaseDaoImpl.kt
诚如我个人项目这个文件，我不太会实现

**Comment by vincentlauvlwj** [comment]
我的意见是，你不需要 `BaseDao` 这种东西，因为就算写了，也就是这样而已：

```kotlin
open class BaseDao<E : BaseEntity<E>>(
    protected val table: Table<E>
) {
    fun add(entity: E): Int {
        return table.add(entity)
    }

    fun update(entity: E): Int {
        return entity.flushChanges()
    }

    fun delete(id: Long): Int {
        return table.delete { it.primaryKey eq id }
    }

    fun updateById(entity: E): Int {
        return entity.flushChanges()
    }

    fun findList(): List<E> {
        return table.findAll();
    }
}
```

既然每个函数里面都只有一行代码，那么有没有 `BaseDao` 又有什么区别呢。

Ktorm 提供的 API 已经足够简洁和灵活，直接使用它们就可以很方便地操作数据库了，没必要增加一层没必要的封装。另外，从传统三层架构的角度来看，Ktorm 本身就可以认为是 DAO 层了，所以你更没有必要自己再写一层 DAO。

注意到你用的是 Spring Boot，可以参考这个项目，看看如何正确地在 Spring Boot 中使用 Ktorm：https://github.com/vincentlauvlwj/ktorm-example-spring-boot

**Comment by UIdoer** [comment]
1，如果没有传统三层，如何实现spring多数据的自动切换？ 2，传统三层有他的必要的吧？比如复杂的业务，服务调服务？你的建议是直接使用事务就撸起袖子写dsl？那复用性我也没有更好的实现方式。希望你在你的ktorm.kiuwj.me中提及。谢谢。 3，还是谢谢你的回复，大神都是有耐心和足够的乐于分享的。不愧是大佬！ 4，希望你事业顺利，身体安康(ღ˘⌣˘ღ)------------------ 原始邮件 ------------------
发件人: "Vincent Lau"<notifications@github.com>
发送时间: 2020年1月8日(星期三) 晚上9:43
收件人: "vincentlauvlwj/Ktorm"<Ktorm@noreply.github.com>;
抄送: "UIdoer"<xian-zi-ming@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vincentlauvlwj/Ktorm] BaseDaoImpl 怎么搞？ (#74)



我的意见是，你不需要 BaseDao 这种东西，因为就算写了，也就是这样而已：
 open class BaseDao<E : BaseEntity<E>>(     protected val table: Table<E> ) {     fun add(entity: E): Int {         return table.add(entity)     }     fun update(entity: E): Int {         return entity.flushChanges()     }     fun delete(id: Long): Int {         return table.delete { it.primaryKey eq id }     }     fun updateById(entity: E): Int {         return entity.flushChanges()     }     fun findList(): List<E> {         return table.findAll();     } }
 
既然每个函数里面都只有一行代码，那么有没有 BaseDao 又有什么区别呢。
 
Ktorm 提供的 API 已经足够简洁和灵活，直接使用它们就可以很方便地操作数据库了，没必要增加一层没必要的封装。另外，从传统三层架构的角度来看，Ktorm 本身就可以认为是 DAO 层了，所以你更没有必要自己再写一层 DAO。
 
注意到你用的是 Spring Boot，可以参考这个项目，看看如何正确地在 Spring Boot 中使用 Ktorm：https://github.com/vincentlauvlwj/ktorm-example-spring-boot
 
&mdash;

**Comment by vincentlauvlwj** [comment]
> 如果没有传统三层，如何实现spring多数据的自动切换？

这个问题我没看懂，可以重新说明一下？

> 传统三层有他的必要的吧？比如复杂的业务，服务调服务？你的建议是直接使用事务就撸起袖子写dsl？那复用性我也没有更好的实现方式。希望你在你的ktorm.kiuwj.me中提及。谢谢。

我没有否认三层架构的意思，但是如果你的某一层里面的函数都是在两三行以内就可以实现的，这就说明这一层的复用性不够好，这样子的“封装”就是完全没有必要的。

比如你项目中的 `BaseDao`，我们可以发现，如果使用 Ktorm 的话，里面的方法基本都只需要一行，在这种情况下，有没有这个类又有什么区别呢？

当然，我也不建议直接在业务层里面混入大量的 SQL DSL，如果你的代码逻辑复杂的话，这可能会给可读性造成一些干扰。我推荐的是适当的分层，你可以灵活组织你的代码，把使用 SQL DSL 的地方单独分为一层，但是不必过于死板，像那种每个方法都只有一行的 `BaseDao`，大可以抛弃。

至于 ktorm.liuwj.me，这个是 Ktorm 的官网，里面的内容是 Ktorm 的使用文档，而你的疑问只是关于代码分层，跟 Ktorm 其实没有太大关系，换个框架也是一样的，不适合放在那里说明，有问题你可以直接问我。

**Comment by vincentlauvlwj** [comment]
题外话，我博客里这堆留言是你发的吧，邮箱服务挂了是什么意思？

![image](https://user-images.githubusercontent.com/10897214/72001200-e4423100-327f-11ea-8952-c2e2044786cb.png)
