### ISSUE TITLE
怎么将查询出来的结果json化呢

### ISSUE THREAD

**Issue by HsiangSun** [vincentlauvlwj/Ktorm#75]
大佬，你好。我就想问问怎么将查询出来结果使用fastJSON返回给客户端。kotlin萌新一个，大佬不要骂我，跪谢啦😭

**Comment by vincentlauvlwj** [comment]
客气了，有问题尽管提问

Ktorm 暂时不支持 fast json 哦，但是你可以使用 Jackson，这里有说明：https://ktorm.liuwj.me/zh-cn/entities-and-column-binding.html#%E5%BA%8F%E5%88%97%E5%8C%96
