### ISSUE TITLE
datetime column throws exception

### ISSUE THREAD

**Issue by clydebarrow** [vincentlauvlwj/Ktorm#79]
I have database columns with mysql type `datetime`. If I declare the ktorm members as `LocalDate` it works, but of course I get no time information. Declaring them as `LocalDateTime` and using the `datetime` extension function causes this execption:

````
Caused by: java.lang.IllegalArgumentException: Class should have a single no-arg constructor: class java.time.LocalDateTime
	at kotlin.reflect.full.KClasses.createInstance(KClasses.kt:281)
	at me.liuwj.ktorm.schema.ColumnBindingHandlerKt.getDefaultValue(ColumnBindingHandler.kt:109)
	at me.liuwj.ktorm.entity.EntityImplementation.getDefaultValue(EntityImplementation.kt:111)
````

**Comment by vincentlauvlwj** [comment]
If the column value can be null, please mark the property's type as nullable: `LocalDateTime?`, otherwise Ktorm will try to return a default value when you read the property. See https://ktorm.liuwj.me/en/entities-and-column-binding.html#Getting-and-Setting-Properties

**Comment by clydebarrow** [comment]
It's not nullable.
````
mysql> describe wp_posts;
+-----------------------+-----------------+------+-----+---------------------+----------------+
| Field                 | Type            | Null | Key | Default             | Extra          |
+-----------------------+-----------------+------+-----+---------------------+----------------+
| ID                    | bigint unsigned | NO   | PRI | NULL                | auto_increment |
| post_author           | bigint unsigned | NO   | MUL | 0                   |                |
| post_date             | datetime        | NO   |     | 0000-00-00 00:00:00 |                |
````

**Comment by vincentlauvlwj** [comment]
Alright. Can you show me the code that can reproduce this exception?

**Comment by clydebarrow** [comment]
So here's what's happening (the same thing happens with `date` as `datetime` in fact). I have two database tables, one with an id that references the other. The child table is like this:
````
interface WpPostMeta: Entity<WpPostMeta> {
    companion object: Entity.Factory<WpPostMeta>()
    var metaId: Long
    var wpPost: WpPost
    var metaKey: String
    var metaValue: String
}

open class WpPostMetas: Table<WpPostMeta>("wp_postmeta") {
    companion object: WpPostMetas()
    val metaId by long("meta_id").primaryKey().bindTo { it.metaId }
    val postId by long("post_id").references(WpPosts) { it.wpPost }
    val metaValue by varchar("meta_value").bindTo { it.metaValue }
    val metaKey by varchar("meta_key").bindTo { it.metaKey }
    val wpPost get() = postId.referenceTable as WpPost
}
````
I have a function that does a select on this table and then gets the row in the other table that it references, using the `val wpPost` element. This is where it fails - the proxy object returned by that has only the id, no other data. If I explicitly look up the other table, it's fine:
````
                .map { WpPostMetas.createEntity(it) }
                //.map {(it.wpPost) }  // this doesn't work
                .map {(WpPosts.findById(it.wpPost.id)!!) } // This works
````
Maybe I'm misunderstanding what `    val wpPost get() = postId.referenceTable as WpPost
` is supposed to do. I thought it would get me the referenced object.

**Comment by vincentlauvlwj** [comment]
If you are using SQL DSL, you need to join the referenced table and select its columns explicitly. 

`val wpPost get() = postId.referenceTable as WpPost` doesn't do anything, just ignore it.

**Comment by vincentlauvlwj** [comment]
Please show me the code of the query before you call `.map { WpPostsMetas.createEntity(it) }`

**Comment by clydebarrow** [comment]
This is the complete query.
````
        fun findFirstAfter(number: Int): ShopOrder? {
            return WpPostMetas.select()
                .where { (WpPostMetas.metaKey eq ORDER_NUMBER) and (WpPostMetas.metaValue greaterEq number.toString()) }
                .orderBy(WpPostMetas.metaValue.asc())
                .limit(0, 1)
                .map { WpPostMetas.createEntity(it) }
                //.map { ShopOrder(it.wpPost) }
                .map { ShopOrder(WpPosts.findById(it.wpPost.id)!!) }
                .firstOrNull()
        }

````

**Comment by vincentlauvlwj** [comment]
It recommended to use sequence APIs whenever possible: 

```kotlin
fun findFirstAfter(number: Int): ShopOrder? {
    return WpPostMetas.asSequence()
        .filter { it.metaKey eq ORDER_NUMBER }
        .filter { it.metaValue greaterEq number.toString() }
        .sortedBy { it.metaValue }
        .take(1)
        .map { ShopOrder(it.wpPost) }
        .firstOrNull()
}
```

**Comment by vincentlauvlwj** [comment]
Sequence APIs will auto join the referenced table while SQL DSL won't, so if you are using SQL DSL, you have to explicitly join the referenced table and select its columns. That's why we recommend to use sequence APIs as the first choice. 

Equivlent code using SQL DSL: 

```kotlin
fun findFirstAfter(number: Int): ShopOrder? {
    return WpPostMetas
        .leftJoin(WpPosts, on = WpPostMetas.postId eq WpPosts.id)
        .select(WpPostMetas.columns + WpPosts.columns)
        .where { (WpPostMetas.metaKey eq ORDER_NUMBER) and (WpPostMetas.metaValue greaterEq number.toString()) }
        .orderBy(WpPostMetas.metaValue.asc())
        .limit(0, 1)
        .map { row ->
            WpPostMetas.createEntity(row).apply { 
                wpPost = WpPosts.createEntity(row)
            }
        }
        .map { ShopOrder(it.wpPost) }
        .firstOrNull()
}
```

**Comment by clydebarrow** [comment]
> It recommended to use sequence APIs whenever possible:

Yes, but when the table is huge that's not a good option :-( This is a legacy database that exploded in size and the schema is simply awful. I have ended up extracting the relevant items from the meta table and creating a new table that just maps the order numbers to the main table. Apart from anything else that turned out to be almost essential since the meta table values are all strings, so the ordering is wrong.

Anyway, thanks for the explanation - it makes more sense now.
