### ISSUE TITLE
Following README.md (#entities-and-column-binding) cannot create entity instance.

### ISSUE THREAD

**Issue by Yunato** [vincentlauvlwj/Ktorm#81]
I think the method that creates an instance of an entity is missing.
It is necessary to define the ```Entity.Factory<T>()``` as a singleton method in the definition of entities in these code.

```
interface Department : Entity<Department> {
  companion object : Entity.Factory<Department>() // here
  val id: Int
  var name: String
  var location: String
}
```

**Comment by vincentlauvlwj** [comment]
Yes, you are right. I will update the document.
