### ISSUE TITLE
Use a custom Database instance for my model

### ISSUE THREAD

**Issue by isaac-weisberg** [vincentlauvlwj/Ktorm#82]
So the `Database.connect` call produces a new instance of `Database`. However I am noting that `Table.add` and many other methods of it probably rely on the singleton version of the `Database` and they don't require me specifying the database or connection object to use.

How can I make the `Table` use my own, custom instance of the database in order to do transactions, insertions and stuff?

**Comment by vincentlauvlwj** [comment]
In the current version (before 2.7), we can use the `db { }` syntax to specify the database instance to use while performing our operations. For example: 

```kotlin
database {
    val employees = Employees.asSequence()
        .filter { it.departmentId eq 1 }
        .toList()

    Employees.add(..)
}
```

But in version 2.7, I'm doing a refactoring of the code, removing the golbal database instance. The syntax will be: 

```kotlin
val sequence = database.sequenceOf(Employees)
val employees = sequence.filter { it.departmentId eq 1 }.toList()
sequence.add(..)
```

Ktorm 2.7 will be released soon!!

**Comment by isaac-weisberg** [comment]
good shit, monsieur!
