### ISSUE TITLE
One to many relationships in both directions

### ISSUE THREAD

**Issue by clydebarrow** [vincentlauvlwj/Ktorm#83]
Given these entities:
````
interface Department : Entity<Department> {    
val id: Int    
var name: String    
var location: String
}
interface Employee : Entity<Employee> {    
val id: Int?   
 var name: String   
 var job: String   
 var manager: Employee?    
var hireDate: LocalDate   
 var salary: Long   
 var department: Department
}

````
The `Employee` has a reference to the `Department` and I understand from the docs that when fetching `Employees` a join will be done to get the `Department` as well. What about the other way - can we have in `Department` a list of `Employees`?

````
interface Department : Entity<Department> {    
val id: Int    
var name: String    
var location: String
var employees: List<Employee>
}
````
Right now I'm doing it by a `findList{}`.

**Comment by vincentlauvlwj** [comment]
Write an extension function `lazyFetch`: 

```kotlin
inline fun <reified T> Entity<*>.lazyFetch(name: String, loader: () -> T): T {
    return this[name] as? T ?: loader().also { this[name] = it }
}
```

With this function, we can implement one-to-many relationships. Write a property with a custom getter and call the function in the getter: 

```kotlin
interface Department : Entity<Department> {
    val id: Int
    val name: String
    val location: String
    val employees get() = lazyFetch("employees") { Employees.findList { it.departmentId eq id } }
}
```

Hope it is helpful to you!

**Comment by gsy13213009** [comment]
大佬牛批，中文不容易搜到该问题，有木有啥论坛或者什么的可以供大家讨论🙈  @vincentlauvlwj

**Comment by vincentlauvlwj** [comment]
@gsy13213009 有问题可以直接在 GitHub issue 上提，论坛的话，我比较常上的是 Kotlin 中文社区的论坛，也可以在上面 @ 我 https://discuss.kotliner.cn/
