### ISSUE TITLE
where 条件里的优先级问题

### ISSUE THREAD

**Issue by JensenQi** [vincentlauvlwj/Ktorm#88]
`Users.select(blah blah).where { Users.id eq id and Users.isRemove eq false }`
对应生成的 SQL 为
`select blah blah from users where ((users.id = ?) and users.is_remove) = ? `
而不是
`select blah blah from users where ((users.id = ?) and (users.is_remove= ?)) `
虽然
`Users.select(blah blah).where { (Users.id eq id) and (Users.isRemove eq false) }` 
这样能得到期望的结果，但是这样写感觉有点丑陋啊

**Comment by vincentlauvlwj** [comment]
这个是没有办法的事情，文档里面有提到 https://ktorm.liuwj.me/zh-cn/operators.html#%E8%BF%90%E7%AE%97%E7%AC%A6%E4%BC%98%E5%85%88%E7%BA%A7

毕竟 `eq`, `and` 并不是真正的运算符，它们只是 Kotlin 中的 infix 函数而已，因此必须遵守 Kotlin 的规则。除了加括号，我们没有办法干涉到普通 infix 函数的结合顺序。

如果你觉得这样有点丑陋，可以考虑换一种写法：

```kotlin
database
    .sequenceOf(Users)
    .filter { it.id eq id }
    .filterNot { it.isRemove }
    .mapColumns2 { Pair(it.id, it.name) }
    .forEach { (id, name) -> 
        println("$id:$name")
    }
```

你看这样是不是好一点呢？

**Comment by JensenQi** [comment]
> 这个是没有办法的事情，文档里面有提到 https://ktorm.liuwj.me/zh-cn/operators.html#%E8%BF%90%E7%AE%97%E7%AC%A6%E4%BC%98%E5%85%88%E7%BA%A7
> 
> 毕竟 `eq`, `and` 并不是真正的运算符，它们只是 Kotlin 中的 infix 函数而已，因此必须遵守 Kotlin 的规则。除了加括号，我们没有办法干涉到普通 infix 函数的结合顺序。
> 
> 如果你觉得加括号有点丑陋，可以考虑换一种写法：
> 
> ```kotlin
> database
>     .sequenceOf(Users)
>     .filter { it.id eq id }
>     .filterNot { it.isRemove }
>     .mapColumns2 { Pair(it.id, it.name) }
>     .forEach { (id, name) -> 
>         println("$id:$name")
>     }
> ```
> 
> 你看这样是不是好一点呢？

谢谢大佬的回复，我想有没有可能在 infix 函数阶段生成逆波兰式，最后 SQL 生成阶段再去计算表达式的值，我先看看项目的源码吧 :D
