### ISSUE TITLE
insertAndGenerateKey don't working.

### ISSUE THREAD

**Issue by ddk9499** [vincentlauvlwj/Ktorm#90]
Is there any reason why used `database.useTransaction` method instead of `database.useConnection` while we call [`Database.insertAndGenerateKey(table, block)`](https://github.com/vincentlauvlwj/Ktorm/blob/a696dc7814856bb2e0dd249eb0ae27b06983a64f/ktorm-core/src/main/kotlin/me/liuwj/ktorm/database/SqlDialect.kt#L69)? Is it tested? Because, in my case, but log says everything is okey(printing effects count and generated key), transaction don't be committed.
Can anyone clarify situation. Is there bug or it's my wrong?

Database: PostgreSQL
Ktorm version: 2.7
pgDriverVersion: 42.2.9

**Comment by ddk9499** [comment]
I have override this method in my [`OwnDialect`](https://gist.github.com/ddk9499/b339b0ef80c2b56b4dbde6faf9bd06cd) and it works. I think there's bug in library.

**Comment by vincentlauvlwj** [comment]
Yes, you've found a legacy bug. I will fix it. Thank you.

**Comment by vincentlauvlwj** [comment]
Sorry that my tests didn't cover this case. I've fixed it. Please upgrade to version 2.7.1
