### ISSUE TITLE
can we have a default db back?

### ISSUE THREAD

**Issue by schmeic** [vincentlauvlwj/Ktorm#91]
Would it be possible to have both the old default db functionality together with the new syntax to specify the db? So:
database.from(Employees).select()
would use the specified db,

and:
from(Employees).select()
would use the default db?

I think the use case of having a single db is much more common than using multiple dbs in a project, so the new syntax seems unnecessarily cumbersome.

**Comment by vincentlauvlwj** [comment]
These APIs will be reimplemented and published as a separated module, which is ktorm-global. See https://ktorm.liuwj.me/en/about-deprecating-database-global.html#ktorm-global

**Comment by schmeic** [comment]
Great, thanks!

**Comment by vincentlauvlwj** [comment]
Added in version 3.0.0
