### ISSUE TITLE
Making a table instance available in the Query object

### ISSUE THREAD

**Issue by ashokgelal** [vincentlauvlwj/Ktorm#92]
In practice, I've been finding more and more painful to not have the current table in the query instance. It is doable without it by, for an example, resorting back to `sequenceOf`. But, in some cases, this limits the flexibility of what we can do and makes the APIs comparatively less delightful. Here's an example of a pagination method that I'm writing:

This is what I want:

```kotlin

inline fun <reified E : Entity<E>, reified T : BaseTable<E>> Query.paginate(): Paginator<E> {
    val perPage = 15
    val currentPage = 1
    limit(currentPage - 1, perPage + 1)
    return map {
       table.createEntity(it) // this is not possible
    }.let {
        Paginator(it, perPage)
    }
}


Users.findById(1)
            .account
            .organizations()
            .orderByName()
            .applyFilter(params("search", "trashed"))
            .paginate()

```

But this is what I've to do:

```kotlin

inline fun <reified E : Entity<E>, reified T : BaseTable<E>> Query.paginate(table: T): Paginator<E> {
    val perPage = 15
    val currentPage = 1
    limit(currentPage - 1, perPage + 1)
    return map {
        table.createEntity(it)
    }.let {
        Paginator(it, perPage)
    }
}

Users.findById(1)
            .account
            .organizations()
            .orderByName()
            .applyFilter(params("search", "trashed"))
            .paginate(Organizations)

```

This is just a small example but I've more of such Query extension methods where I'd have to pass around the table as well.

I've looked at the code and looks like passing the current table to a query is very easy. Unless I'm overlooking something big.

**Comment by vincentlauvlwj** [comment]
I don't think it's appropriate to pass a table object to a `Query`. For example, consider the code below, that we are joining many tables in the query, which table object should be the *current table* in this case?

```kotlin
data class Names(val name: String?, val managerName: String?, val departmentName: String?)

val emp = Employees.aliased("emp")
val mgr = Employees.aliased("mgr")
val dept = Departments.aliased("dept")

val results = database
    .from(emp)
    .leftJoin(dept, on = emp.departmentId eq dept.id)
    .leftJoin(mgr, on = emp.managerId eq mgr.id)
    .select(emp.name, mgr.name, dept.name)
    .orderBy(emp.id.asc())
    .map { row -> 
        Names(
            name = row[emp.name],
            managerName = row[mgr.name],
            departmentName = row[dept.name]
        )
    }
```

**Comment by vincentlauvlwj** [comment]
Instead, why not make your functions as extensions of `EntitySequence`?

**Comment by ashokgelal** [comment]
I realized that it may not work for multiple tables. I just wanted to have your thoughts. I'm finding extensions with `EntitySequence` less flexible at times. Will keep digging into it. Thank you!
