### ISSUE TITLE
Getting random rows

### ISSUE THREAD

**Issue by ashokgelal** [vincentlauvlwj/Ktorm#93]
What would be an efficient way to get random rows from a table? I saw `rand()` function being mentioned but don't know how to call it or use it. Thank you!

**Comment by vincentlauvlwj** [comment]
`rand()` can be used as a selected column, for example `Employees.select(rand())`. It can also be used in expressions, eg. `Employees.select(Employees.name).where { rand() greater 0 }`

**Comment by ashokgelal** [comment]
Thanks! So is there a way to fetch random rows without having to falling back to Kotlin shuffle/random functions?

**Comment by vincentlauvlwj** [comment]
Try this: 

```kotlin
Employees.select().orderBy(rand()).limit(0, 1)
```

Generated SQL: 

```sql
select * from employee order by rand() limit 0, 1
```

**Comment by ashokgelal** [comment]
According to this, that is not very efficient: https://jan.kneschke.de/projects/mysql/order-by-rand/

**Comment by ashokgelal** [comment]
I finally tried the above solution that you proposed but I get this error:

> Required `OrderByExpression` found `FunctionExpression<Double>`

**Comment by ashokgelal** [comment]
It works by converting `rand()` to an `OrderByExpression` first though:

```kotlin
val randExpression = OrderByExpression(rand().asExpression(), OrderType.ASCENDING)
Employees.select().orderBy(randExpression).limit(0, 1)
```

**Comment by vincentlauvlwj** [comment]
Oh, sorry. I forgot `asc()`/`desc()`: 

```kotlin
Employees.select().orderBy(rand().asc()).limit(0, 1)
```
