### ISSUE TITLE
Add support for soft-deleting

### ISSUE THREAD

**Issue by raderio** [vincentlauvlwj/Ktorm#96]
In some applications, you don’t want to, or you are not allowed to permanently remove a record from the database. But you still need to remove or hide records which are no longer active. One example could be a user account which you want to keep because it is linked to other business objects which are still used.

Typical story: after an entity is marked with `deleted=true`, it should not be visible anywhere, except specially chosen places.

Something like
```
Users notDeletedUsers = Users.filter((u) -> u.DELETED.eq(false))
from(notDeletedUsers).select(notDeletedUsers.ID, notDeletedUsers.TYPE)
```

**Comment by vincentlauvlwj** [comment]
Equavalent code using Ktorm: 

```kotlin
val notDeletedUsers = database.sequenceOf(Users).filterNot { it.deleted }
notDeletedUsers.filter { .. }.mapColumns { .. }
```
