### ISSUE TITLE
Add support for transaction isolation level

### ISSUE THREAD

**Issue by raderio** [vincentlauvlwj/Ktorm#97]
Please add support for transaction isolation levels per transaction.

```
database.withTransaction(isolation = Isolation.SERIALIZABLE) { txn ->
    // ...
}
```

https://en.wikipedia.org/wiki/Isolation_(database_systems)

Slick supports this
https://github.com/slick/slick/issues/218

Spring also supports this
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/transaction/annotation/Transactional.html#isolation--

**Comment by vincentlauvlwj** [comment]
Ktorm already supports transaction isolations, you can write code like: 

```kotlin
database.userTransaction(isolation = TransactionIsolation.REPEATABLE_READ) { tx -> 

}
```
